package main

import (
	"fmt"
	"go/format"
	"os"
	"path/filepath"

	"opendesk/pkg/officialconfig"
)

const generatedFilename = "zz_generated_product_config.go"

func main() {
	sourcePath := filepath.Join("..", "..", "apps", "opendesk", "assets", officialconfig.BaseName+".odcfg")
	payload, err := os.ReadFile(sourcePath)
	if err != nil {
		fail("read %s: %v", sourcePath, err)
	}
	if _, err := officialconfig.Decode(payload); err != nil {
		fail("validate %s: %v", sourcePath, err)
	}
	source := []byte(fmt.Sprintf(`// Code generated by go generate ./internal/officialassets; DO NOT EDIT.

package officialassets

const generatedProductConfig = %q
`, string(payload)))
	formatted, err := format.Source(source)
	if err != nil {
		fail("format generated source: %v", err)
	}
	temporary, err := os.CreateTemp(".", ".product-config-*.go")
	if err != nil {
		fail("create temporary output: %v", err)
	}
	temporaryPath := temporary.Name()
	defer os.Remove(temporaryPath)
	if err := temporary.Chmod(0o644); err != nil {
		temporary.Close()
		fail("set temporary output mode: %v", err)
	}
	if _, err := temporary.Write(formatted); err != nil {
		temporary.Close()
		fail("write temporary output: %v", err)
	}
	if err := temporary.Sync(); err != nil {
		temporary.Close()
		fail("sync temporary output: %v", err)
	}
	if err := temporary.Close(); err != nil {
		fail("close temporary output: %v", err)
	}
	if err := os.Rename(temporaryPath, generatedFilename); err != nil {
		fail("publish %s: %v", generatedFilename, err)
	}
}

func fail(format string, args ...any) {
	fmt.Fprintf(os.Stderr, format+"\n", args...)
	os.Exit(1)
}
