// Code generated from assets/toolbar-icons-v1.json; DO NOT EDIT.
package toolbar

type iconDefinition struct {
	token        string
	presentation IconPresentation
}

var generatedIcons = map[string]iconDefinition{
	"play.fill":                         {token: "play-fill", presentation: IconPresentation{SystemSymbol: "play.fill", Scale: 1.00, OffsetX: 0.50, OffsetY: 0.00}},
	"pause.fill":                        {token: "pause-fill", presentation: IconPresentation{SystemSymbol: "pause.fill", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"stop.fill":                         {token: "stop-fill", presentation: IconPresentation{SystemSymbol: "stop.fill", Scale: 1.15, OffsetX: 0.00, OffsetY: 0.00}},
	"gearshape.fill":                    {token: "gearshape-fill", presentation: IconPresentation{SystemSymbol: "gearshape.fill", Scale: 1.08, OffsetX: 0.00, OffsetY: 0.00}},
	"paperplane.fill":                   {token: "paperplane-fill", presentation: IconPresentation{SystemSymbol: "paperplane.fill", Scale: 1.00, OffsetX: -0.25, OffsetY: 0.25}},
	"timer":                             {token: "timer", presentation: IconPresentation{SystemSymbol: "timer", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"forward.fill":                      {token: "forward-fill", presentation: IconPresentation{SystemSymbol: "forward.fill", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"backward.fill":                     {token: "backward-fill", presentation: IconPresentation{SystemSymbol: "backward.fill", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"forward.end.fill":                  {token: "forward-end-fill", presentation: IconPresentation{SystemSymbol: "forward.end.fill", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"backward.end.fill":                 {token: "backward-end-fill", presentation: IconPresentation{SystemSymbol: "backward.end.fill", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"arrow.clockwise":                   {token: "arrow-clockwise", presentation: IconPresentation{SystemSymbol: "arrow.clockwise", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"arrow.counterclockwise":            {token: "arrow-counterclockwise", presentation: IconPresentation{SystemSymbol: "arrow.counterclockwise", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"repeat":                            {token: "repeat", presentation: IconPresentation{SystemSymbol: "repeat", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"shuffle":                           {token: "shuffle", presentation: IconPresentation{SystemSymbol: "shuffle", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"eject.fill":                        {token: "eject-fill", presentation: IconPresentation{SystemSymbol: "eject.fill", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"power":                             {token: "power", presentation: IconPresentation{SystemSymbol: "power", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"xmark":                             {token: "xmark", presentation: IconPresentation{SystemSymbol: "xmark", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"checkmark":                         {token: "checkmark", presentation: IconPresentation{SystemSymbol: "checkmark", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"plus":                              {token: "plus", presentation: IconPresentation{SystemSymbol: "plus", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"minus":                             {token: "minus", presentation: IconPresentation{SystemSymbol: "minus", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"ellipsis":                          {token: "ellipsis", presentation: IconPresentation{SystemSymbol: "ellipsis", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"ai.assistant":                      {token: "ai-assistant", presentation: IconPresentation{SystemSymbol: "brain", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"ai.generate":                       {token: "ai-generate", presentation: IconPresentation{SystemSymbol: "wand.and.rays", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"ai.analyze":                        {token: "ai-analyze", presentation: IconPresentation{SystemSymbol: "doc.text.magnifyingglass", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"ai.search":                         {token: "ai-search", presentation: IconPresentation{SystemSymbol: "text.magnifyingglass", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"automation.run":                    {token: "automation-run", presentation: IconPresentation{SystemSymbol: "arrow.triangle.2.circlepath", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"automation.schedule":               {token: "automation-schedule", presentation: IconPresentation{SystemSymbol: "clock.arrow.circlepath", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"automation.trigger":                {token: "automation-trigger", presentation: IconPresentation{SystemSymbol: "bolt.circle.fill", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"automation.configure":              {token: "automation-configure", presentation: IconPresentation{SystemSymbol: "gearshape.2.fill", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"automation.review":                 {token: "automation-review", presentation: IconPresentation{SystemSymbol: "rectangle.and.hand.point.up.left.fill", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"automation.approve":                {token: "automation-approve", presentation: IconPresentation{SystemSymbol: "hand.tap.fill", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"magnifyingglass":                   {token: "magnifyingglass", presentation: IconPresentation{SystemSymbol: "magnifyingglass", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"slider.horizontal.3":               {token: "slider-horizontal-3", presentation: IconPresentation{SystemSymbol: "slider.horizontal.3", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"info.circle":                       {token: "info-circle", presentation: IconPresentation{SystemSymbol: "info.circle", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"questionmark.circle":               {token: "questionmark-circle", presentation: IconPresentation{SystemSymbol: "questionmark.circle", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"exclamationmark.triangle":          {token: "exclamationmark-triangle", presentation: IconPresentation{SystemSymbol: "exclamationmark.triangle", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"bell.fill":                         {token: "bell-fill", presentation: IconPresentation{SystemSymbol: "bell.fill", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"bell.slash.fill":                   {token: "bell-slash-fill", presentation: IconPresentation{SystemSymbol: "bell.slash.fill", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"trash.fill":                        {token: "trash-fill", presentation: IconPresentation{SystemSymbol: "trash.fill", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"square.and.arrow.up":               {token: "square-and-arrow-up", presentation: IconPresentation{SystemSymbol: "square.and.arrow.up", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"square.and.arrow.down":             {token: "square-and-arrow-down", presentation: IconPresentation{SystemSymbol: "square.and.arrow.down", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"doc.on.doc":                        {token: "doc-on-doc", presentation: IconPresentation{SystemSymbol: "doc.on.doc", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"folder.fill":                       {token: "folder-fill", presentation: IconPresentation{SystemSymbol: "folder.fill", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"tray.fill":                         {token: "tray-fill", presentation: IconPresentation{SystemSymbol: "tray.fill", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"envelope.fill":                     {token: "envelope-fill", presentation: IconPresentation{SystemSymbol: "envelope.fill", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"message.fill":                      {token: "message-fill", presentation: IconPresentation{SystemSymbol: "message.fill", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"bubble.left.and.bubble.right.fill": {token: "bubble-left-and-bubble-right-fill", presentation: IconPresentation{SystemSymbol: "bubble.left.and.bubble.right.fill", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"phone.fill":                        {token: "phone-fill", presentation: IconPresentation{SystemSymbol: "phone.fill", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"video.fill":                        {token: "video-fill", presentation: IconPresentation{SystemSymbol: "video.fill", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"mic.fill":                          {token: "mic-fill", presentation: IconPresentation{SystemSymbol: "mic.fill", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"speaker.wave.2.fill":               {token: "speaker-wave-2-fill", presentation: IconPresentation{SystemSymbol: "speaker.wave.2.fill", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"headphones":                        {token: "headphones", presentation: IconPresentation{SystemSymbol: "headphones", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"at":                                {token: "at", presentation: IconPresentation{SystemSymbol: "at", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"link":                              {token: "link", presentation: IconPresentation{SystemSymbol: "link", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"person.crop.circle.fill":           {token: "person-crop-circle-fill", presentation: IconPresentation{SystemSymbol: "person.crop.circle.fill", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"person.2.fill":                     {token: "person-2-fill", presentation: IconPresentation{SystemSymbol: "person.2.fill", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"person.badge.plus":                 {token: "person-badge-plus", presentation: IconPresentation{SystemSymbol: "person.badge.plus", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"person.badge.minus":                {token: "person-badge-minus", presentation: IconPresentation{SystemSymbol: "person.badge.minus", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"heart.fill":                        {token: "heart-fill", presentation: IconPresentation{SystemSymbol: "heart.fill", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"star.fill":                         {token: "star-fill", presentation: IconPresentation{SystemSymbol: "star.fill", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"bookmark.fill":                     {token: "bookmark-fill", presentation: IconPresentation{SystemSymbol: "bookmark.fill", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"flag.fill":                         {token: "flag-fill", presentation: IconPresentation{SystemSymbol: "flag.fill", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"pin.fill":                          {token: "pin-fill", presentation: IconPresentation{SystemSymbol: "pin.fill", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"location.fill":                     {token: "location-fill", presentation: IconPresentation{SystemSymbol: "location.fill", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"map.fill":                          {token: "map-fill", presentation: IconPresentation{SystemSymbol: "map.fill", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"calendar":                          {token: "calendar", presentation: IconPresentation{SystemSymbol: "calendar", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"clock.fill":                        {token: "clock-fill", presentation: IconPresentation{SystemSymbol: "clock.fill", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"alarm.fill":                        {token: "alarm-fill", presentation: IconPresentation{SystemSymbol: "alarm.fill", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"bolt.fill":                         {token: "bolt-fill", presentation: IconPresentation{SystemSymbol: "bolt.fill", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"lightbulb.fill":                    {token: "lightbulb-fill", presentation: IconPresentation{SystemSymbol: "lightbulb.fill", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"lock.fill":                         {token: "lock-fill", presentation: IconPresentation{SystemSymbol: "lock.fill", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"lock.open.fill":                    {token: "lock-open-fill", presentation: IconPresentation{SystemSymbol: "lock.open.fill", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"key.fill":                          {token: "key-fill", presentation: IconPresentation{SystemSymbol: "key.fill", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"eye.fill":                          {token: "eye-fill", presentation: IconPresentation{SystemSymbol: "eye.fill", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"eye.slash.fill":                    {token: "eye-slash-fill", presentation: IconPresentation{SystemSymbol: "eye.slash.fill", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"camera.fill":                       {token: "camera-fill", presentation: IconPresentation{SystemSymbol: "camera.fill", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"camera.rotate.fill":                {token: "camera-rotate-fill", presentation: IconPresentation{SystemSymbol: "camera.rotate.fill", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"photo.fill":                        {token: "photo-fill", presentation: IconPresentation{SystemSymbol: "photo.fill", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"photo.on.rectangle":                {token: "photo-on-rectangle", presentation: IconPresentation{SystemSymbol: "photo.on.rectangle", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"video.circle.fill":                 {token: "video-circle-fill", presentation: IconPresentation{SystemSymbol: "video.circle.fill", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"play.rectangle.fill":               {token: "play-rectangle-fill", presentation: IconPresentation{SystemSymbol: "play.rectangle.fill", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"pause.rectangle.fill":              {token: "pause-rectangle-fill", presentation: IconPresentation{SystemSymbol: "pause.rectangle.fill", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"music.note":                        {token: "music-note", presentation: IconPresentation{SystemSymbol: "music.note", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"music.note.list":                   {token: "music-note-list", presentation: IconPresentation{SystemSymbol: "music.note.list", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"waveform":                          {token: "waveform", presentation: IconPresentation{SystemSymbol: "waveform", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"radio.fill":                        {token: "radio-fill", presentation: IconPresentation{SystemSymbol: "radio.fill", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"tv.fill":                           {token: "tv-fill", presentation: IconPresentation{SystemSymbol: "tv.fill", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"gamecontroller.fill":               {token: "gamecontroller-fill", presentation: IconPresentation{SystemSymbol: "gamecontroller.fill", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"film.fill":                         {token: "film-fill", presentation: IconPresentation{SystemSymbol: "film.fill", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"sparkles":                          {token: "sparkles", presentation: IconPresentation{SystemSymbol: "sparkles", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"wand.and.stars":                    {token: "wand-and-stars", presentation: IconPresentation{SystemSymbol: "wand.and.stars", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"paintbrush.fill":                   {token: "paintbrush-fill", presentation: IconPresentation{SystemSymbol: "paintbrush.fill", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"pencil":                            {token: "pencil", presentation: IconPresentation{SystemSymbol: "pencil", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"pencil.tip.crop.circle":            {token: "pencil-tip-crop-circle", presentation: IconPresentation{SystemSymbol: "pencil.tip.crop.circle", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"scissors":                          {token: "scissors", presentation: IconPresentation{SystemSymbol: "scissors", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"crop":                              {token: "crop", presentation: IconPresentation{SystemSymbol: "crop", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"textformat":                        {token: "textformat", presentation: IconPresentation{SystemSymbol: "textformat", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"text.alignleft":                    {token: "text-alignleft", presentation: IconPresentation{SystemSymbol: "text.alignleft", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"text.aligncenter":                  {token: "text-aligncenter", presentation: IconPresentation{SystemSymbol: "text.aligncenter", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"text.alignright":                   {token: "text-alignright", presentation: IconPresentation{SystemSymbol: "text.alignright", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"bold":                              {token: "bold", presentation: IconPresentation{SystemSymbol: "bold", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"italic":                            {token: "italic", presentation: IconPresentation{SystemSymbol: "italic", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"underline":                         {token: "underline", presentation: IconPresentation{SystemSymbol: "underline", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"sum":                               {token: "sum", presentation: IconPresentation{SystemSymbol: "sum", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"function":                          {token: "function", presentation: IconPresentation{SystemSymbol: "function", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"doc.fill":                          {token: "doc-fill", presentation: IconPresentation{SystemSymbol: "doc.fill", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"doc.text.fill":                     {token: "doc-text-fill", presentation: IconPresentation{SystemSymbol: "doc.text.fill", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"doc.richtext.fill":                 {token: "doc-richtext-fill", presentation: IconPresentation{SystemSymbol: "doc.richtext.fill", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"doc.append.fill":                   {token: "doc-append-fill", presentation: IconPresentation{SystemSymbol: "doc.append.fill", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"folder.badge.plus":                 {token: "folder-badge-plus", presentation: IconPresentation{SystemSymbol: "folder.badge.plus", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"folder.badge.minus":                {token: "folder-badge-minus", presentation: IconPresentation{SystemSymbol: "folder.badge.minus", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"tray.and.arrow.down.fill":          {token: "tray-and-arrow-down-fill", presentation: IconPresentation{SystemSymbol: "tray.and.arrow.down.fill", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"tray.and.arrow.up.fill":            {token: "tray-and-arrow-up-fill", presentation: IconPresentation{SystemSymbol: "tray.and.arrow.up.fill", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"externaldrive.fill":                {token: "externaldrive-fill", presentation: IconPresentation{SystemSymbol: "externaldrive.fill", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"internaldrive.fill":                {token: "internaldrive-fill", presentation: IconPresentation{SystemSymbol: "internaldrive.fill", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"icloud.fill":                       {token: "icloud-fill", presentation: IconPresentation{SystemSymbol: "icloud.fill", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"archivebox.fill":                   {token: "archivebox-fill", presentation: IconPresentation{SystemSymbol: "archivebox.fill", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"shippingbox.fill":                  {token: "shippingbox-fill", presentation: IconPresentation{SystemSymbol: "shippingbox.fill", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"printer.fill":                      {token: "printer-fill", presentation: IconPresentation{SystemSymbol: "printer.fill", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"viewfinder":                        {token: "viewfinder", presentation: IconPresentation{SystemSymbol: "viewfinder", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"qrcode":                            {token: "qrcode", presentation: IconPresentation{SystemSymbol: "qrcode", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"barcode":                           {token: "barcode", presentation: IconPresentation{SystemSymbol: "barcode", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"creditcard.fill":                   {token: "creditcard-fill", presentation: IconPresentation{SystemSymbol: "creditcard.fill", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"cart.fill":                         {token: "cart-fill", presentation: IconPresentation{SystemSymbol: "cart.fill", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"bag.fill":                          {token: "bag-fill", presentation: IconPresentation{SystemSymbol: "bag.fill", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"gift.fill":                         {token: "gift-fill", presentation: IconPresentation{SystemSymbol: "gift.fill", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"tag.fill":                          {token: "tag-fill", presentation: IconPresentation{SystemSymbol: "tag.fill", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"list.bullet":                       {token: "list-bullet", presentation: IconPresentation{SystemSymbol: "list.bullet", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"square.grid.2x2.fill":              {token: "square-grid-2x2-fill", presentation: IconPresentation{SystemSymbol: "square.grid.2x2.fill", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"tablecells.fill":                   {token: "tablecells-fill", presentation: IconPresentation{SystemSymbol: "tablecells.fill", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"chart.bar.fill":                    {token: "chart-bar-fill", presentation: IconPresentation{SystemSymbol: "chart.bar.fill", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"chart.pie.fill":                    {token: "chart-pie-fill", presentation: IconPresentation{SystemSymbol: "chart.pie.fill", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"chart.line.uptrend.xyaxis":         {token: "chart-line-uptrend-xyaxis", presentation: IconPresentation{SystemSymbol: "chart.line.uptrend.xyaxis", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"wifi":                              {token: "wifi", presentation: IconPresentation{SystemSymbol: "wifi", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"antenna.radiowaves.left.and.right": {token: "antenna-radiowaves-left-and-right", presentation: IconPresentation{SystemSymbol: "antenna.radiowaves.left.and.right", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"network":                           {token: "network", presentation: IconPresentation{SystemSymbol: "network", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"battery.100":                       {token: "battery-100", presentation: IconPresentation{SystemSymbol: "battery.100", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"cpu":                               {token: "cpu", presentation: IconPresentation{SystemSymbol: "cpu", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"memorychip":                        {token: "memorychip", presentation: IconPresentation{SystemSymbol: "memorychip", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"desktopcomputer":                   {token: "desktopcomputer", presentation: IconPresentation{SystemSymbol: "desktopcomputer", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"laptopcomputer":                    {token: "laptopcomputer", presentation: IconPresentation{SystemSymbol: "laptopcomputer", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"keyboard":                          {token: "keyboard", presentation: IconPresentation{SystemSymbol: "keyboard", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"computermouse.fill":                {token: "computermouse-fill", presentation: IconPresentation{SystemSymbol: "computermouse.fill", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"display":                           {token: "display", presentation: IconPresentation{SystemSymbol: "display", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"iphone":                            {token: "iphone", presentation: IconPresentation{SystemSymbol: "iphone", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"ipad":                              {token: "ipad", presentation: IconPresentation{SystemSymbol: "ipad", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"applewatch":                        {token: "applewatch", presentation: IconPresentation{SystemSymbol: "applewatch", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"house.fill":                        {token: "house-fill", presentation: IconPresentation{SystemSymbol: "house.fill", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"building.2.fill":                   {token: "building-2-fill", presentation: IconPresentation{SystemSymbol: "building.2.fill", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"car.fill":                          {token: "car-fill", presentation: IconPresentation{SystemSymbol: "car.fill", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"airplane":                          {token: "airplane", presentation: IconPresentation{SystemSymbol: "airplane", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"tram.fill":                         {token: "tram-fill", presentation: IconPresentation{SystemSymbol: "tram.fill", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"bus.fill":                          {token: "bus-fill", presentation: IconPresentation{SystemSymbol: "bus.fill", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"bicycle":                           {token: "bicycle", presentation: IconPresentation{SystemSymbol: "bicycle", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"figure.walk":                       {token: "figure-walk", presentation: IconPresentation{SystemSymbol: "figure.walk", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"sun.max.fill":                      {token: "sun-max-fill", presentation: IconPresentation{SystemSymbol: "sun.max.fill", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"moon.fill":                         {token: "moon-fill", presentation: IconPresentation{SystemSymbol: "moon.fill", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"cloud.sun.fill":                    {token: "cloud-sun-fill", presentation: IconPresentation{SystemSymbol: "cloud.sun.fill", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"cloud.rain.fill":                   {token: "cloud-rain-fill", presentation: IconPresentation{SystemSymbol: "cloud.rain.fill", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
	"shield.fill":                       {token: "shield-fill", presentation: IconPresentation{SystemSymbol: "shield.fill", Scale: 1.00, OffsetX: 0.00, OffsetY: 0.00}},
}

func IconToken(name string) (string, bool) { value, ok := generatedIcons[name]; return value.token, ok }
func IconPresentationFor(name string) (IconPresentation, bool) {
	value, ok := generatedIcons[name]
	return value.presentation, ok
}
func IconNames() []string {
	return []string{"ai.analyze", "ai.assistant", "ai.generate", "ai.search", "airplane", "alarm.fill", "antenna.radiowaves.left.and.right", "applewatch", "archivebox.fill", "arrow.clockwise", "arrow.counterclockwise", "at", "automation.approve", "automation.configure", "automation.review", "automation.run", "automation.schedule", "automation.trigger", "backward.end.fill", "backward.fill", "bag.fill", "barcode", "battery.100", "bell.fill", "bell.slash.fill", "bicycle", "bold", "bolt.fill", "bookmark.fill", "bubble.left.and.bubble.right.fill", "building.2.fill", "bus.fill", "calendar", "camera.fill", "camera.rotate.fill", "car.fill", "cart.fill", "chart.bar.fill", "chart.line.uptrend.xyaxis", "chart.pie.fill", "checkmark", "clock.fill", "cloud.rain.fill", "cloud.sun.fill", "computermouse.fill", "cpu", "creditcard.fill", "crop", "desktopcomputer", "display", "doc.append.fill", "doc.fill", "doc.on.doc", "doc.richtext.fill", "doc.text.fill", "eject.fill", "ellipsis", "envelope.fill", "exclamationmark.triangle", "externaldrive.fill", "eye.fill", "eye.slash.fill", "figure.walk", "film.fill", "flag.fill", "folder.badge.minus", "folder.badge.plus", "folder.fill", "forward.end.fill", "forward.fill", "function", "gamecontroller.fill", "gearshape.fill", "gift.fill", "headphones", "heart.fill", "house.fill", "icloud.fill", "info.circle", "internaldrive.fill", "ipad", "iphone", "italic", "key.fill", "keyboard", "laptopcomputer", "lightbulb.fill", "link", "list.bullet", "location.fill", "lock.fill", "lock.open.fill", "magnifyingglass", "map.fill", "memorychip", "message.fill", "mic.fill", "minus", "moon.fill", "music.note", "music.note.list", "network", "paintbrush.fill", "paperplane.fill", "pause.fill", "pause.rectangle.fill", "pencil", "pencil.tip.crop.circle", "person.2.fill", "person.badge.minus", "person.badge.plus", "person.crop.circle.fill", "phone.fill", "photo.fill", "photo.on.rectangle", "pin.fill", "play.fill", "play.rectangle.fill", "plus", "power", "printer.fill", "qrcode", "questionmark.circle", "radio.fill", "repeat", "scissors", "shield.fill", "shippingbox.fill", "shuffle", "slider.horizontal.3", "sparkles", "speaker.wave.2.fill", "square.and.arrow.down", "square.and.arrow.up", "square.grid.2x2.fill", "star.fill", "stop.fill", "sum", "sun.max.fill", "tablecells.fill", "tag.fill", "text.aligncenter", "text.alignleft", "text.alignright", "textformat", "timer", "tram.fill", "trash.fill", "tray.and.arrow.down.fill", "tray.and.arrow.up.fill", "tray.fill", "tv.fill", "underline", "video.circle.fill", "video.fill", "viewfinder", "wand.and.stars", "waveform", "wifi", "xmark"}
}
