const entry = File.read('examples/mac/wechat_steps/main.js');
if (!entry) throw new Error('缺少入口脚本: examples/mac/wechat_steps/main.js');
const patchedEntry = entry.replace('await shared.main();', '');

const probeCode = [
  "shared.runtimeConfig.sendAuditPath = '.runtime/temp/mac/stage_c_search_input_audit.jsonl';",
  "shared.runtimeConfig.permissionSection = 'baseline';",
  "shared.runtimeConfig.stepMode = 'bundle_search_chat';",
  "shared.ensureDirForFile = function ensureDirForFile(path) { return String(path || ''); };",
  "shared.writeJsonWithEnsure = async function writeJsonWithEnsure(path, payload) { await File.write(path, JSON.stringify(payload, null, 2)); };",
  "shared.searchInputProbeMain = async function searchInputProbeMain() {",
  "  const context = await shared.buildInitialContext();",
  "  let failedStep = '';",
  "  let failureCause = '';",
  "  try {",
  "    await shared.locate_search_area(context);",
  "    await shared.focus_search_input(context);",
  "    await shared.type_search_query(context);",
  "  } catch (err) {",
  "    failedStep = shared.buildStepEvidenceSummary(context)?.latestFailure?.stepId || 'search_input_probe';",
  "    failureCause = err && err.message ? err.message : String(err);",
  "  }",
  "  const stepEvidenceSummary = shared.buildStepEvidenceSummary(context);",
  "  const latest = stepEvidenceSummary.latestFailure || null;",
  "  const out = {",
  "    timestamp: new Date().toISOString(),",
  "    stage: 'C-search-input',",
  "    scenario: 'wechat_search_input_probe',",
  "    reportPath: '.runtime/temp/mac/stage_c_search_input_report.json',",
  "    auditPath: shared.runtimeConfig.sendAuditPath,",
  "    targetChatName: shared.runtimeConfig.targetChatName,",
  "    searchResolved: context.searchResolved || null,",
  "    searchInputMode: context.searchInputMode || null,",
  "    searchQueryVisibleCheck: context.searchQueryVisibleCheck || null,",
  "    statusSummary: {",
  "      searchAreaLocated: Boolean(stepEvidenceSummary.byStep?.locate_search_area?.lastSuccess) || Boolean(context.searchResolved?.box),",
  "      searchInputFocused: Boolean(stepEvidenceSummary.byStep?.focus_search_input?.lastSuccess),",
  "      searchQueryTyped: Boolean(stepEvidenceSummary.byStep?.type_search_query?.lastSuccess),",
  "      queryVisible: Boolean(context.searchQueryVisibleCheck?.ok),",
  "    },",
  "    stepEvidenceSummary,",
  "    failedStep: failedStep || latest?.stepId || '',",
  "    failureCause: failureCause || latest?.error || '',",
  "    fallbackOrDegraded: false,",
  "    minimalFailureBoundary: latest?.stepId === 'type_search_query' ? 'query_visible' : (latest?.stepId || ''),",
  "    failureType: latest?.stepId === 'type_search_query' ? '输入成功/可见性判定抖动' : '',",
  "    nextFixSuggestions: [",
  "      '扩大搜索框局部截图并双阶段 OCR 校验，区分输入失败与 OCR 误判',",
  "      '若 clipboard 输入成功但 queryVisible 仍失败，继续放宽 token 级 fuzzy 匹配并记录 capturePath'",
  "    ]",
  "  };",
  "  await shared.writeJsonWithEnsure(out.reportPath, out);",
  "  console.log(JSON.stringify({ reportPath: out.reportPath, auditPath: out.auditPath, statusSummary: out.statusSummary, stepEvidenceSummary, failedStep: out.failedStep, failureCause: out.failureCause, minimalFailureBoundary: out.minimalFailureBoundary, failureType: out.failureType }, null, 2));",
  "};",
  "await shared.searchInputProbeMain();"
].join('\n');

await eval('(async () => {\n' + patchedEntry + '\n' + probeCode + '\n})()');
