const entry = File.read('examples/mac/wechat_steps/main.js');
if (!entry) throw new Error('缺少入口脚本: examples/mac/wechat_steps/main.js');
const patchedEntry = entry.replace('await shared.main();', '');

const probeCode = [
  "shared.runtimeConfig.sendAuditPath = '.runtime/temp/mac/stage_c_open_chat_header_audit.jsonl';",
  "shared.runtimeConfig.permissionSection = 'baseline';",
  "shared.runtimeConfig.stepMode = 'open_chat_verify_header';",
  "shared.ensureDirForFile = function ensureDirForFile(path) { return String(path || ''); };",
  "shared.writeJsonWithEnsure = async function writeJsonWithEnsure(path, payload) { await File.write(path, JSON.stringify(payload, null, 2)); };",
  "shared.openChatHeaderProbeMain = async function openChatHeaderProbeMain() {",
  "  const context = await shared.buildInitialContext();",
  "  let failedStep = '';",
  "  let failureCause = '';",
  "  try {",
  "    await shared.locate_conversation_list(context);",
  "    await shared.open_chat(context);",
  "    await shared.verify_chat_header(context);",
  "  } catch (err) {",
  "    failedStep = shared.buildStepEvidenceSummary(context)?.latestFailure?.stepId || 'open_chat_header_probe';",
  "    failureCause = err && err.message ? err.message : String(err);",
  "  }",
  "  const stepEvidenceSummary = shared.buildStepEvidenceSummary(context);",
  "  const latest = stepEvidenceSummary.latestFailure || null;",
  "  const minimalFailureBoundary = latest?.stepId === 'open_chat' ? 'search_result_row_geometry' : (latest?.stepId || 'unknown');",
  "  const failureType = latest?.stepId === 'open_chat' ? '识别策略不足' : 'header 校验链路待加强';",
  "  const out = {",
  "    timestamp: new Date().toISOString(),",
  "    stage: 'C-open-chat-header',",
  "    scenario: 'wechat_open_chat_header_probe',",
  "    reportPath: '.runtime/temp/mac/stage_c_open_chat_header_report.json',",
  "    auditPath: shared.runtimeConfig.sendAuditPath,",
  "    targetChatName: shared.runtimeConfig.targetChatName,",
  "    targetSelection: context.targetSelection || null,",
  "    openChatPoint: context.openChatPoint || null,",
  "    headerCheck: context.headerCheck || null,",
  "    statusSummary: {",
  "      conversationListLocated: Boolean(stepEvidenceSummary.byStep?.locate_conversation_list?.lastSuccess) || Boolean(context.conversationResolved?.box),",
  "      openChatSucceeded: Boolean(stepEvidenceSummary.byStep?.open_chat?.lastSuccess),",
  "      headerVerified: Boolean(stepEvidenceSummary.byStep?.verify_chat_header?.lastSuccess) || Boolean(context.headerCheck?.ok),",
  "    },",
  "    stepEvidenceSummary,",
  "    failedStep: failedStep || latest?.stepId || '',",
  "    failureCause: failureCause || latest?.error || '',",
  "    fallbackOrDegraded: Boolean(context.targetSelection?.degradedSearchFallback) || Boolean(context.searchResultRow?.fallback),",
  "    minimalFailureBoundary,",
  "    failureType,",
  "    nextFixSuggestions: [",
  "      '若 open_chat 仍失败，根因仍在 search_result_row 真正可点击几何，继续专注 search_result_row_probe',",
  "      '若 open_chat 成功但 verify_chat_header 失败，收窄 header OCR 区域并补点击后等待策略',",
  "      '只有 headerVerified=true 后，才继续 focus_input_probe'",
  "    ]",
  "  };",
  "  await shared.writeJsonWithEnsure(out.reportPath, out);",
  "  console.log(JSON.stringify({ reportPath: out.reportPath, auditPath: out.auditPath, statusSummary: out.statusSummary, stepEvidenceSummary, failedStep: out.failedStep, failureCause: out.failureCause, fallbackOrDegraded: out.fallbackOrDegraded, minimalFailureBoundary: out.minimalFailureBoundary, failureType: out.failureType }, null, 2));",
  "};",
  "await shared.openChatHeaderProbeMain();"
].join('\n');

await eval('(async () => {\n' + patchedEntry + '\n' + probeCode + '\n})()');
