const entry = File.read('examples/mac/wechat_steps/main.js');
if (!entry) throw new Error('缺少入口脚本: examples/mac/wechat_steps/main.js');
const patchedEntry = entry.replace('await shared.main();', '');

const probeCode = [
  "shared.ensureDirForFile = function ensureDirForFile(path) {",
  "  return String(path || '');",
  "};",
  "shared.writeJsonWithEnsure = async function writeJsonWithEnsure(path, payload) {",
  "  shared.ensureDirForFile(path);",
  "  await File.write(path, JSON.stringify(payload, null, 2));",
  "};",
  "shared.runtimeConfig.sendAuditPath = '.runtime/runs/macos_v1/stage_c/audit.jsonl';",
  "shared.runtimeConfig.permissionSection = 'baseline';",
  "shared.runtimeConfig.stepMode = 'open_chat_verify_header_focus_input';",
  "shared.writeStageCReport = async function writeStageCReport(context) {",
  "  const stepEvidenceSummary = shared.buildStepEvidenceSummary(context);",
  "  const failed = stepEvidenceSummary.latestFailure || null;",
  "  const statusSummary = {",
  "    openChatSucceeded: Boolean(stepEvidenceSummary.byStep?.open_chat?.lastSuccess) || Boolean(context?.openChatPoint),",
  "    headerVerified: Boolean(context?.headerCheck?.ok),",
  "    inputFocused: Boolean(stepEvidenceSummary.byStep?.focus_input?.lastSuccess) || Boolean(context?.focusPoint),",
  "    adapterReadyForSendFlow: Boolean(context?.headerCheck?.ok) && (Boolean(stepEvidenceSummary.byStep?.focus_input?.lastSuccess) || Boolean(context?.focusPoint))",
  "  };",
  "  const out = {",
  "    timestamp: new Date().toISOString(),",
  "    stage: 'C',",
  "    scenario: 'wechat_high_complexity_adapter',",
  "    mode: 'open_chat_verify_header_focus_input',",
  "    config: shared.runtimeConfig,",
  "    reportPath: '.runtime/runs/macos_v1/stage_c/report.json',",
  "    auditPath: shared.runtimeConfig.sendAuditPath,",
  "    artifactRunRoot: context.artifactBundle?.runRoot || shared.runtimeConfig.artifactRunRoot,",
  "    window: context.win,",
  "    targetSelection: context.targetSelection || null,",
  "    openChatPoint: context.openChatPoint || null,",
  "    focusPoint: context.focusPoint || null,",
  "    headerCheck: context.headerCheck || null,",
  "    statusSummary,",
  "    stepEvidenceSummary,",
  "    failedStep: failed?.stepId || '',",
  "    failureCause: failed?.error || '',",
  "    fallbackOrDegraded: Boolean(failed?.extra?.fallbackUsed) || Boolean(failed?.extra?.degradedSearchFallback),",
  "    nextFixSuggestions: [",
  "      '如果 search_result_row probe 仅有文本命中无 bbox，继续强化真实会话行几何识别，禁止 OCR-only 点击',",
  "      '如果 open_chat 成功但 header 校验失败，改为更窄的标题语义裁剪与点击后稳定等待，再做 OCR/模板双验证',",
  "      '如果 header 通过但 focus_input 不稳，单独新增 focused input probe，验证输入框模板偏移和点击点是否需要 app-specific 微调'",
  "    ]",
  "  };",
  "  await shared.writeJsonWithEnsure(out.reportPath, out);",
  "  console.log(JSON.stringify({ reportPath: out.reportPath, auditPath: out.auditPath, statusSummary, stepEvidenceSummary, failedStep: out.failedStep, failureCause: out.failureCause, fallbackOrDegraded: out.fallbackOrDegraded }, null, 2));",
  "  return out.reportPath;",
  "};",
  "shared.stageCMain = async function stageCMain() {",
  "  const context = await shared.buildInitialContext();",
  "  await shared.locate_conversation_list(context);",
  "  await shared.open_chat(context);",
  "  await shared.verify_chat_header(context);",
  "  await shared.focus_input(context);",
  "  return shared.writeStageCReport(context);",
  "};",
  "await shared.stageCMain();"
].join('\n');

await eval('(async () => {\n' + patchedEntry + '\n' + probeCode + '\n})()');
