const entry = File.read('examples/mac/wechat_steps/main.js');
if (!entry) throw new Error('缺少入口脚本: examples/mac/wechat_steps/main.js');
const patchedEntry = entry.replace('await shared.main();', '');

const probeCode = [
  "shared.runtimeConfig.sendAuditPath = '.runtime/temp/mac/stage_c_focus_input_audit.jsonl';",
  "shared.runtimeConfig.permissionSection = 'baseline';",
  "shared.runtimeConfig.stepMode = 'bundle_open_and_focus_input';",
  "shared.ensureDirForFile = function ensureDirForFile(path) { return String(path || ''); };",
  "shared.writeJsonWithEnsure = async function writeJsonWithEnsure(path, payload) { await File.write(path, JSON.stringify(payload, null, 2)); };",
  "shared.focusInputProbeMain = async function focusInputProbeMain() {",
  "  const context = await shared.buildInitialContext();",
  "  let failedStep = '';",
  "  let failureCause = '';",
  "  try {",
  "    await shared.locate_conversation_list(context);",
  "    await shared.open_chat(context);",
  "    await shared.verify_chat_header(context);",
  "    await shared.focus_input(context);",
  "  } catch (err) {",
  "    failedStep = shared.buildStepEvidenceSummary(context)?.latestFailure?.stepId || 'focus_input_probe';",
  "    failureCause = err && err.message ? err.message : String(err);",
  "  }",
  "  const stepEvidenceSummary = shared.buildStepEvidenceSummary(context);",
  "  const latest = stepEvidenceSummary.latestFailure || null;",
  "  let minimalFailureBoundary = latest?.stepId || '';",
  "  let failureType = '识别策略不足';",
  "  if (latest?.stepId === 'open_chat') minimalFailureBoundary = 'search_result_row_geometry';",
  "  if (latest?.stepId === 'verify_chat_header') minimalFailureBoundary = 'header_verification';",
  "  if (latest?.stepId === 'focus_input') minimalFailureBoundary = 'input_focus';",
  "  if (latest?.stepId === 'open_chat') failureType = '识别策略不足';",
  "  else if (latest?.stepId === 'verify_chat_header') failureType = 'header 校验链路待加强';",
  "  else if (latest?.stepId === 'focus_input') failureType = '输入框模板定位或点击策略不足';",
  "  const out = {",
  "    timestamp: new Date().toISOString(),",
  "    stage: 'C-focus-input',",
  "    scenario: 'wechat_focus_input_probe',",
  "    reportPath: '.runtime/temp/mac/stage_c_focus_input_report.json',",
  "    auditPath: shared.runtimeConfig.sendAuditPath,",
  "    targetChatName: shared.runtimeConfig.targetChatName,",
  "    targetSelection: context.targetSelection || null,",
  "    openChatPoint: context.openChatPoint || null,",
  "    headerCheck: context.headerCheck || null,",
  "    focusPoint: context.focusPoint || null,",
  "    statusSummary: {",
  "      conversationListLocated: Boolean(stepEvidenceSummary.byStep?.locate_conversation_list?.lastSuccess) || Boolean(context.conversationResolved?.box),",
  "      openChatSucceeded: Boolean(stepEvidenceSummary.byStep?.open_chat?.lastSuccess),",
  "      headerVerified: Boolean(stepEvidenceSummary.byStep?.verify_chat_header?.lastSuccess) || Boolean(context.headerCheck?.ok),",
  "      inputFocused: Boolean(stepEvidenceSummary.byStep?.focus_input?.lastSuccess) || Boolean(context.focusPoint),",
  "    },",
  "    stepEvidenceSummary,",
  "    failedStep: failedStep || latest?.stepId || '',",
  "    failureCause: failureCause || latest?.error || '',",
  "    fallbackOrDegraded: Boolean(context.targetSelection?.degradedSearchFallback) || Boolean(context.searchResultRow?.fallback),",
  "    minimalFailureBoundary,",
  "    failureType,",
  "    nextFixSuggestions: [",
  "      '如果仍卡在 open_chat，先不要空转 focus_input，继续压缩 search_result_row 几何识别问题',",
  "      '如果 header 已通过而 focus_input 失败，优先检查 input_area 模板重定位与点击点是否偏离输入框中心',",
  "      'focus_input 通过后再继续 type_draft，不把高级发送链路混进当前 probe'",
  "    ]",
  "  };",
  "  await shared.writeJsonWithEnsure(out.reportPath, out);",
  "  console.log(JSON.stringify({ reportPath: out.reportPath, auditPath: out.auditPath, statusSummary: out.statusSummary, stepEvidenceSummary, failedStep: out.failedStep, failureCause: out.failureCause, fallbackOrDegraded: out.fallbackOrDegraded, minimalFailureBoundary: out.minimalFailureBoundary, failureType: out.failureType }, null, 2));",
  "};",
  "await shared.focusInputProbeMain();"
].join('\n');

await eval('(async () => {\n' + patchedEntry + '\n' + probeCode + '\n})()');
