/* Standalone prototype oracle. NOT an OpenDesk Runtime Geometry replacement. */
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.MeasureModel=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
function finite(v,name){if(!Number.isFinite(v))throw new TypeError(name+' must be finite');return v;}
function rect(r){['x','y','width','height'].forEach(k=>finite(r[k],k));if(r.width<=0||r.height<=0)throw new RangeError('Positive rectangle dimensions required');return r;}
function edges(r){return {left:r.x,top:r.y,right:r.x+r.width,bottom:r.y+r.height};}
function area(r){return Math.max(0,r.width)*Math.max(0,r.height);}
function intersection(a,b){const w=Math.max(0,Math.min(a.x+a.width,b.x+b.width)-Math.max(a.x,b.x)),h=Math.max(0,Math.min(a.y+a.height,b.y+b.height)-Math.max(a.y,b.y));return {width:w,height:h,area:w*h};}
function relative(t,r){rect(r);rect(t);const a=edges(t),b=edges(r),ix=intersection(t,r);return {absolute:{...t},relative:{x:t.x-r.x,y:t.y-r.y,width:t.width,height:t.height},percentage:{x:100*(t.x-r.x)/r.width,y:100*(t.y-r.y)/r.height,width:100*t.width/r.width,height:100*t.height/r.height},signedEdges:{left:a.left-b.left,top:a.top-b.top,right:b.right-a.right,bottom:b.bottom-a.bottom},centerOffset:{x:t.x+t.width/2-(r.x+r.width/2),y:t.y+t.height/2-(r.y+r.height/2)},alignmentDelta:{left:a.left-b.left,top:a.top-b.top,right:a.right-b.right,bottom:a.bottom-b.bottom},aspectRatio:t.width/t.height,areaRatio:area(t)/area(r),coverageRatio:ix.area/area(r),insideRatio:ix.area/area(t)};}
function pointRelative(p,r){rect(r);finite(p.x,'x');finite(p.y,'y');return {absolute:{...p},relative:{x:p.x-r.x,y:p.y-r.y},percentage:{x:100*(p.x-r.x)/r.width,y:100*(p.y-r.y)/r.height}};}
function points(a,b){finite(a.x,'a.x');finite(a.y,'a.y');finite(b.x,'b.x');finite(b.y,'b.y');const dx=b.x-a.x,dy=b.y-a.y;return {dx,dy,horizontalDistance:Math.abs(dx),verticalDistance:Math.abs(dy),straightDistance:Math.hypot(dx,dy)};}
function rectangles(a,b){rect(a);rect(b);const ea=edges(a),eb=edges(b),i=intersection(a,b);return {a:{...a},b:{...b},horizontalGap:Math.max(0,Math.max(a.x,b.x)-Math.min(ea.right,eb.right)),verticalGap:Math.max(0,Math.max(a.y,b.y)-Math.min(ea.bottom,eb.bottom)),projectionOverlapX:i.width,projectionOverlapY:i.height,overlapArea:i.area,centerDelta:{x:b.x+b.width/2-a.x-a.width/2,y:b.y+b.height/2-a.y-a.height/2},bRelativeToA:relative(b,a)};}
function pixelFloor(v,p,o,scale){const nearest=Math.round(v),tolerance=8*Number.EPSILON*Math.max(1,Math.abs(p),Math.abs(o))*scale;return Math.floor(Math.abs(v-nearest)<=tolerance?nearest:v);}
function logicalToPixel(p,tiles){for(const tile of tiles){const r=tile.logicalBounds;if(p.x>=r.x&&p.x<r.x+r.width&&p.y>=r.y&&p.y<r.y+r.height){const sx=tile.pixelSize.width/r.width,sy=tile.pixelSize.height/r.height;return {displayId:tile.displayId,x:pixelFloor((p.x-r.x)*sx,p.x,r.x,sx),y:pixelFloor((p.y-r.y)*sy,p.y,r.y,sy),scaleX:sx,scaleY:sy};}}return null;}
function placePanel(view,w,h,targets,previous){const m=12,places=[{corner:'tr',x:view.width-w-m,y:m},{corner:'tl',x:m,y:m},{corner:'br',x:view.width-w-m,y:view.height-h-m},{corner:'bl',x:m,y:view.height-h-m}].map(p=>({...p,x:Math.max(0,p.x),y:Math.max(0,p.y),width:Math.min(w,view.width),height:Math.min(h,view.height)}));const overlap=p=>targets.reduce((s,t)=>s+intersection(p,t).area,0);const prev=places.find(p=>p.corner===previous);if(prev&&overlap(prev)===0)return {...prev,limited:false};places.sort((a,b)=>overlap(a)-overlap(b));return {...places[0],limited:overlap(places[0])>0};}
return Object.freeze({rect,edges,area,intersection,relative,pointRelative,points,rectangles,logicalToPixel,placePanel});
});
