package measurement

import (
	"bytes"
	"context"
	"errors"
	"image"
	"image/color"
	"image/png"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"testing"
	"time"

	"opendesk/pkg/customui"
)

type sessionCapture struct{mu sync.Mutex;count int}
func(c *sessionCapture)Count()int{c.mu.Lock();defer c.mu.Unlock();return c.count}
func(c *sessionCapture)Capture(_ context.Context,target string)(CaptureFrame,error){c.mu.Lock();defer c.mu.Unlock();c.count++;if target==""{target="target"};origin:=Point{X:-100,Y:20};logical:=Size{Width:100,Height:50};pixels:=PixelSize{Width:200,Height:100};bounds:=Rect{X:-80,Y:25,Width:60,Height:30};if target=="other"{origin=Point{X:300,Y:-40};logical=Size{Width:120,Height:80};pixels=PixelSize{Width:240,Height:160};bounds=Rect{X:320,Y:-20,Width:70,Height:40}};img:=image.NewRGBA(image.Rect(0,0,pixels.Width,pixels.Height));img.Set(pixels.Width/4,pixels.Height/4,color.RGBA{R:1,G:2,B:3,A:255});var data bytes.Buffer;if err:=png.Encode(&data,img);err!=nil{return CaptureFrame{},err};mapping,err:=NewCaptureMapping(origin,logical,pixels,target+"-display",1);if err!=nil{return CaptureFrame{},err};return CaptureFrame{PNG:data.Bytes(),Snapshot:Snapshot{SampledAt:time.Date(2026,9,14,10,0,c.count,0,time.UTC),Mapping:mapping},Reference:Reference{Type:ReferenceWindowOuter,Bounds:bounds,Window:&WindowIdentity{ID:target,PID:7,Title:"Fixture"}},Targets:[]TargetWindow{{ID:"target",Title:"Fixture",PID:7},{ID:"other",Title:"Other",PID:8}},SelectedTargetID:target,TargetConfirmed:true},nil}
type captureFunc func(context.Context,string)(CaptureFrame,error)
func(fn captureFunc)Capture(ctx context.Context,target string)(CaptureFrame,error){return fn(ctx,target)}
type sessionClipboard struct{mu sync.Mutex;writes []string}
func(c *sessionClipboard)Copy(v string)error{c.mu.Lock();defer c.mu.Unlock();c.writes=append(c.writes,v);return nil}
type createCountingDriver struct{customui.Driver;mu sync.Mutex;creates int}
func(d *createCountingDriver)Create(ctx context.Context,sessionID string,spec customui.WindowSpec,sink func(customui.Event))(customui.DriverWindow,error){d.mu.Lock();d.creates++;d.mu.Unlock();return d.Driver.Create(ctx,sessionID,spec,sink)}
func(d *createCountingDriver)CreateCount()int{d.mu.Lock();defer d.mu.Unlock();return d.creates}
func newSessionService(t *testing.T)(*Service,*customui.MemoryDriver,*sessionCapture,*sessionClipboard){t.Helper();driver:=customui.NewMemoryDriver();capture:=&sessionCapture{};clipboard:=&sessionClipboard{};service,err:=NewService(ServiceOptions{Driver:driver,Capture:capture,Clipboard:clipboard,BaseDir:t.TempDir(),Now:func()time.Time{return time.Date(2026,9,14,11,0,0,0,time.UTC)}});if err!=nil{t.Fatal(err)};return service,driver,capture,clipboard}

func TestServiceReentryUsesSameSessionSnapshotAndSurface(t *testing.T){base:=customui.NewMemoryDriver();driver:=&createCountingDriver{Driver:base};capture:=&sessionCapture{};service,err:=NewService(ServiceOptions{Driver:driver,Capture:capture,Clipboard:&sessionClipboard{},BaseDir:t.TempDir()});if err!=nil{t.Fatal(err)};ctx:=context.Background();if err:=service.Open(ctx,"product-menu");err!=nil{t.Fatal(err)};first:=service.active;window:=first.currentWindow();if err:=service.Open(ctx,"recorder-toolbar");err!=nil{t.Fatal(err)};if service.active!=first||service.active.currentWindow()!=window||capture.Count()!=1||driver.CreateCount()!=1{t.Fatalf("reentry changed lifecycle active=%p first=%p captures=%d creates=%d",service.active,first,capture.Count(),driver.CreateCount())};if err:=service.Close(ctx);err!=nil{t.Fatal(err)};if service.Counts()!=(ServiceCounts{})||base.ResourceCounts().Sinks!=0{t.Fatal("measurement resources leaked")}}
func TestRefreshMutatesSameSurfaceAndMovesBounds(t *testing.T){base:=customui.NewMemoryDriver();driver:=&createCountingDriver{Driver:base};capture:=&sessionCapture{};service,err:=NewService(ServiceOptions{Driver:driver,Capture:capture,Clipboard:&sessionClipboard{},BaseDir:t.TempDir()});if err!=nil{t.Fatal(err)};ctx:=context.Background();if err:=service.Open(ctx,"product-menu");err!=nil{t.Fatal(err)};a:=service.active;window:=a.currentWindow();if err:=a.refresh(ctx,"other");err!=nil{t.Fatal(err)};if a.currentWindow()!=window||driver.CreateCount()!=1||capture.Count()!=2{t.Fatalf("refresh replaced surface same=%v creates=%d captures=%d",a.currentWindow()==window,driver.CreateCount(),capture.Count())};state,err:=window.State(ctx);if err!=nil{t.Fatal(err)};want:=customui.Bounds{X:300,Y:-40,Width:120,Height:80};if state.Bounds!=want{t.Fatalf("bounds=%+v want=%+v",state.Bounds,want)};_=service.Close(ctx)}
func TestWindowReferenceRequiresConfirmationAndManualFallback(t *testing.T){service,_,_,_:=newSessionService(t);ctx:=context.Background();if err:=service.Open(ctx,"product-menu");err!=nil{t.Fatal(err)};a:=service.active;a.targetConfirmed=false;if err:=a.handle(ctx,customui.Event{Type:"measurement.pointerup",Fields:map[string]any{"u":.25,"v":.25}});err!=nil{t.Fatal(err)};if a.result!=nil||!strings.Contains(a.status,"确认"){t.Fatalf("unconfirmed candidate yielded result=%+v status=%q",a.result,a.status)};if err:=a.handle(ctx,customui.Event{Type:"change",TargetID:"referenceType",Value:string(ReferenceManualRegion)});err!=nil{t.Fatal(err)};_=a.handle(ctx,customui.Event{Type:"measurement.pointerdown",Fields:map[string]any{"u":.2,"v":.2}});_=a.handle(ctx,customui.Event{Type:"measurement.pointerup",Fields:map[string]any{"u":.4,"v":.6}});if a.reference.Type!=ReferenceManualRegion{t.Fatalf("manual reference=%+v",a.reference)};_=service.Close(ctx)}
func TestPointRegionTwoPointAndSpacingUseCanonicalSnapshot(t *testing.T){service,_,_,_:=newSessionService(t);ctx:=context.Background();if err:=service.Open(ctx,"product-menu");err!=nil{t.Fatal(err)};a:=service.active;_=a.handle(ctx,customui.Event{Type:"measurement.pointerup",Fields:map[string]any{"u":.25,"v":.25}});if a.result==nil||a.result.Point==nil||a.result.Point.Color==nil||a.result.Point.Color.Hex!="#010203"{t.Fatalf("point=%+v",a.result)};_=a.handle(ctx,customui.Event{Type:"measurement.key",Fields:map[string]any{"key":"2"}});_=a.handle(ctx,customui.Event{Type:"measurement.pointerdown",Fields:map[string]any{"u":.1,"v":.1}});_=a.handle(ctx,customui.Event{Type:"measurement.pointerup",Fields:map[string]any{"u":.5,"v":.5}});before:=a.result.Region.Absolute;_=a.handle(ctx,customui.Event{Type:"measurement.key",Fields:map[string]any{"key":"ArrowRight","shift":true}});if a.result.Region.Absolute.X!=before.X+10{t.Fatalf("shift nudge=%+v",a.result.Region.Absolute)};_=a.handle(ctx,customui.Event{Type:"measurement.key",Fields:map[string]any{"key":"3"}});_=a.handle(ctx,customui.Event{Type:"measurement.pointerup",Fields:map[string]any{"u":.2,"v":.2}});_=a.handle(ctx,customui.Event{Type:"measurement.pointerup",Fields:map[string]any{"u":.6,"v":.7}});if a.result==nil||a.result.TwoPoint==nil||a.result.TwoPoint.Distance<=0{t.Fatalf("twoPoint=%+v",a.result)};_=a.handle(ctx,customui.Event{Type:"measurement.key",Fields:map[string]any{"key":"4"}});_=a.handle(ctx,customui.Event{Type:"measurement.pointerdown",Fields:map[string]any{"u":.1,"v":.1}});_=a.handle(ctx,customui.Event{Type:"measurement.pointerup",Fields:map[string]any{"u":.2,"v":.2}});_=a.handle(ctx,customui.Event{Type:"measurement.pointerdown",Fields:map[string]any{"u":.6,"v":.6}});_=a.handle(ctx,customui.Event{Type:"measurement.pointerup",Fields:map[string]any{"u":.8,"v":.8}});if a.result==nil||a.result.Spacing==nil||a.result.Spacing.Spacing.Horizontal.Relation!="right"{t.Fatalf("spacing=%+v",a.result)};_=service.Close(ctx)}
func TestInspectorCopyAndSavePreserveThreeTiers(t *testing.T){service,_,_,clipboard:=newSessionService(t);ctx:=context.Background();if err:=service.Open(ctx,"product-menu");err!=nil{t.Fatal(err)};a:=service.active;_=a.handle(ctx,customui.Event{Type:"measurement.pointerup",Fields:map[string]any{"u":.25,"v":.25}});for _,id:=range []string{"copyConcise","copyHuman","copyStructured"}{if err:=a.handleClick(ctx,id);err!=nil{t.Fatal(err)}};if len(clipboard.writes)!=3||!strings.Contains(clipboard.writes[0],"ref=")||!strings.Contains(clipboard.writes[1],"坐标空间")||!strings.Contains(clipboard.writes[2],`"kind": "point"`){t.Fatalf("clipboard tiers=%#v",clipboard.writes)};for _,format:=range []string{"concise","human","json"}{a.outputFormat=format;if err:=a.save(ctx);err!=nil{t.Fatal(err)}};files,err:=os.ReadDir(service.saveDir);if err!=nil||len(files)!=3{t.Fatalf("saved files=%d err=%v",len(files),err)};jsonFound:=false;for _,f:=range files{if filepath.Ext(f.Name())==".json"{data,e:=os.ReadFile(filepath.Join(service.saveDir,f.Name()));if e!=nil{t.Fatal(e)};jsonFound=bytes.Contains(data,[]byte(`"coordinateSpace"`))}};if !jsonFound{t.Fatal("structured save missing coordinateSpace")};_=service.Close(ctx)}
func TestOpenAndWaitEscapeCleansUpWithoutClipboardMutation(t *testing.T){service,_,capture,clipboard:=newSessionService(t);ctx,cancel:=context.WithTimeout(context.Background(),time.Second);defer cancel();done:=make(chan error,1);go func(){done<-service.OpenAndWait(ctx,"recorder-toolbar")}();deadline:=time.Now().Add(time.Second);for service.Counts().Sessions==0&&time.Now().Before(deadline){time.Sleep(time.Millisecond)};if service.Counts().Sessions!=1||capture.Count()!=1{t.Fatalf("not open counts=%+v captures=%d",service.Counts(),capture.Count())};if err:=service.active.handle(context.Background(),customui.Event{Type:"measurement.key",Fields:map[string]any{"key":"Escape"}});err!=nil{t.Fatal(err)};select{case err:=<-done:if err!=nil{t.Fatal(err)};case<-time.After(time.Second):t.Fatal("OpenAndWait did not return")};if len(clipboard.writes)!=0||service.Counts()!=(ServiceCounts{}){t.Fatal("escape changed clipboard or leaked")}}
func TestCloseRestoresCapturedWindowAndReportsLimitedRecovery(t *testing.T){for name,restoreErr:=range map[string]error{"restored":nil,"limited":errors.New("window was closed")}{t.Run(name,func(t *testing.T){capture:=&sessionCapture{};restores:=0;service,err:=NewService(ServiceOptions{Driver:customui.NewMemoryDriver(),Clipboard:&sessionClipboard{},BaseDir:t.TempDir(),Capture:captureFunc(func(ctx context.Context,target string)(CaptureFrame,error){f,e:=capture.Capture(ctx,target);f.Restore=func(context.Context)error{restores++;return restoreErr};return f,e})});if err!=nil{t.Fatal(err)};if err:=service.Open(context.Background(),"product-menu");err!=nil{t.Fatal(err)};err=service.Close(context.Background());if restores!=1||service.Counts()!=(ServiceCounts{}){t.Fatalf("restores=%d counts=%+v",restores,service.Counts())};if restoreErr==nil&&err!=nil{t.Fatal(err)};if restoreErr!=nil&&(err==nil||!strings.Contains(err.Error(),"recovery limited")){t.Fatalf("limited err=%v",err)}})}}
