"""In-memory Chromium prototype tests, not native OpenDesk/OS acceptance."""
import json, shutil
from pathlib import Path
from playwright.sync_api import sync_playwright
root = Path(__file__).resolve().parent
repo = root.parents[1]
evidence = repo / '.runtime/tests/desktop-measurement/prototype'
evidence.mkdir(parents=True, exist_ok=True)
results = []; errors = []
def check(name,condition,detail=''):
    results.append({'name':name,'status':'PASS' if condition else 'FAIL','detail':detail})
    if not condition: raise AssertionError(name+': '+detail)
with sync_playwright() as p:
    exe=shutil.which('chromium') or shutil.which('google-chrome')
    browser=p.chromium.launch(**({'executable_path':exe} if exe else {}),args=['--no-sandbox'])
    page=browser.new_page(viewport={'width':1440,'height':960},device_scale_factor=1)
    page.on('pageerror',lambda e:errors.append(str(e)))
    page.set_content((root/'prototype/index.html').read_text(encoding='utf-8'),wait_until='load')
    check('默认测量界面不打开详情',not page.locator('#inspector').is_visible())
    check('默认同时绘制参照与目标',page.locator('#overlay rect[stroke="#298a78"]').count()==1 and page.locator('#overlay rect[stroke="#218ccd"]').count()>=1)
    sid=page.evaluate('MeasureDemo.state.session'); targets=page.evaluate('JSON.stringify(MeasureDemo.state.targets)')
    for entry in ['#entry-dev','#entry-rec','#entry-key']:page.click(entry)
    check('三个网页模拟入口复用同一会话',page.evaluate('MeasureDemo.state.session')==sid and page.evaluate('JSON.stringify(MeasureDemo.state.targets)')==targets)
    page.evaluate("document.getElementById('toast').hidden=true")
    page.screenshot(path=str(evidence/'01-default-region.png'))
    oldref=page.evaluate('JSON.stringify(MeasureDemo.state.ref)')
    st=page.locator('#stage').bounding_box(); page.mouse.move(900,500)
    check('鼠标移动不会切换锁定参照',page.evaluate('JSON.stringify(MeasureDemo.state.ref)')==oldref)
    page.select_option('#fixture','color')
    check('2x冻结源蓝色像素取色',page.evaluate('MeasureDemo.data().result.color.hex')=='#2879D8')
    color=page.evaluate('MeasureDemo.data().result.color')
    check('像素色包含源图坐标与显示器',color['imagePixel']['x']>=0 and color['displayId']=='demo-display-1')
    page.screenshot(path=str(evidence/'04-point-color.png'))
    page.click('#details');check('详情只在用户请求时打开',page.locator('#inspector').is_visible())
    page.keyboard.press('Escape');check('Esc关闭详情而非结束会话',not page.locator('#inspector').is_visible() and page.evaluate('MeasureDemo.state.active'))
    check('打开关闭详情不污染原始取色',page.evaluate('MeasureDemo.data().result.color.hex')==color['hex'])
    page.select_option('#fixture','pp');q=page.evaluate('MeasureDemo.data().pair');check('两点真实样机数据导出距离',abs(q['straightDistance']-300)<1e-8 and q['dx']==240 and q['dy']==180)
    page.select_option('#fixture','rr');q=page.evaluate('MeasureDemo.data().pair');check('两区域间距与重叠分别导出',q['horizontalGap']==18 and q['overlapArea']==0)
    page.select_option('#fixture','overflow');q=page.evaluate('MeasureDemo.data().result');check('越过参照右边缘显示负44',abs(q['signedEdges']['right']+44)<1e-8)
    page.screenshot(path=str(evidence/'02-negative-edge.png'))
    collisions=page.evaluate('''()=>{const h=document.getElementById('hud').getBoundingClientRect();return [...document.querySelectorAll('[data-badge]')].filter(n=>{const b=n.getBoundingClientRect();return Math.min(b.right,h.right)>Math.max(b.left,h.left)&&Math.min(b.bottom,h.bottom)>Math.max(b.top,h.top)}).length}''')
    check('距离标签不藏在角落信息下',collisions==0)
    page.click('#details');page.screenshot(path=str(evidence/'03-details-on-demand.png'));page.click('#details-close')
    for scenario in ['top-left','top-right','bottom-left','bottom-right']:
        page.select_option('#fixture',scenario)
        overlap=page.evaluate('''()=>{const h=document.getElementById('hud').getBoundingClientRect(),s=document.getElementById('stage').getBoundingClientRect(),t=MeasureDemo.state.targets[0],o=MeasureDemo.origin();return MeasureModel.intersection({x:h.x-s.x,y:h.y-s.y,width:h.width,height:h.height},{x:t.x-o.x,y:t.y-o.y,width:t.width,height:t.height}).area}''')
        check('角落避让 '+scenario,overlap==0)
    page.select_option('#display-fixture','negative');page.select_option('#fixture','color');q=page.evaluate('MeasureDemo.data()')
    check('负逻辑坐标仍正确取色',q['result']['absolute']['x']<0 and q['result']['color']['hex']=='#2879D8')
    page.select_option('#display-fixture','mixed');q=page.evaluate('MeasureDemo.data()')
    check('双屏模拟保留不同像素映射',q['snapshot']['displays'][0]['scaleFactor']==1 and q['snapshot']['displays'][1]['scaleFactor']==2)
    page.select_option('#display-fixture','retina');page.select_option('#fixture','region')
    # Exercise drag and resize through actual browser pointer events.
    before=page.evaluate('({...MeasureDemo.state.targets[0]})');o=page.evaluate('MeasureDemo.origin()')
    x=before['x']-o['x']+st['x']+40;y=before['y']-o['y']+st['y']+50
    page.mouse.move(x,y);page.mouse.down();page.mouse.move(x+20,y+15,steps=4);page.mouse.up()
    after=page.evaluate('MeasureDemo.state.targets[0]');check('拖动区域更新位置不改变大小',abs(after['x']-before['x']-20)<1e-7 and after['width']==before['width'])
    handle=page.locator('[data-handle="se"]').bounding_box();page.mouse.move(handle['x']+4,handle['y']+4);page.mouse.down();page.mouse.move(handle['x']+34,handle['y']+24,steps=4);page.mouse.up()
    check('拖动尺寸手柄可调整区域',page.evaluate('MeasureDemo.state.targets[0].width')>after['width'])
    page.locator('#overlay').focus();beforex=page.evaluate('MeasureDemo.state.targets[0].x');page.keyboard.press('ArrowRight')
    check('方向键微调区域一个逻辑单位',page.evaluate('MeasureDemo.state.targets[0].x')==beforex+1)
    page.click('[data-mode="region"]');r=page.evaluate('MeasureDemo.state.ref.bounds');x=r['x']+220;y=r['y']+180+st['y'];page.mouse.move(x,y);page.locator('#overlay').focus()
    c1=page.evaluate('MeasureDemo.state.candidate.width');page.keyboard.press('Tab');c2=page.evaluate('MeasureDemo.state.candidate.width');check('Tab可切换更大候选',c2>c1)
    page.keyboard.down('Alt');check('按住Alt暂停吸附',page.evaluate('MeasureDemo.state.candidate') is None);page.keyboard.up('Alt')
    page.select_option('#fixture','region')
    # Clipboard success is an injected browser adapter test, not system clipboard evidence.
    page.evaluate("Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async t=>{window.testClipboard=t}}})")
    for level in [1,2,3]:
        page.click('#copy');page.click(f'[data-copy="{level}"]');q=page.evaluate('MeasureDemo.state.copied')
        check(f'第{level}档复制经适配器接收',q['status']=='success' and 'desktop-logical' in q['text'] and ('参照' in q['text'] or 'reference' in q['text']),'剪切板适配器为测试替身；不是系统剪切板验收')
    page.evaluate("Object.defineProperty(navigator,'clipboard',{configurable:true,value:undefined})")
    page.click('#copy');page.click('[data-copy="1"]');check('剪切板不可用时显示手动复制而非虚报成功',page.locator('#manual-copy').is_visible() and page.evaluate('MeasureDemo.state.copied.status')=='manual-required');page.click('#manual-close')
    page.click('#details');page.select_option('#save-level','3')
    with page.expect_download() as download_info:page.click('#save')
    download=download_info.value;download.save_as(str(evidence/'export-example.json'));check('保存可解析结构化JSON',json.loads((evidence/'export-example.json').read_text(encoding='utf-8'))['prototypeOnly'] is True)
    snapid=page.evaluate('MeasureDemo.state.snapshot.id');page.select_option('#reference-select','custom');page.click('#reference-apply')
    check('更换参照需显式确认且不更换源快照',page.evaluate('MeasureDemo.state.ref.kind')=='region' and page.evaluate('MeasureDemo.state.snapshot.id')==snapid)
    page.click('#details-close');page.click('#exit');check('退出移除所有测量层并清理样机会话引用',page.locator('#overlay').is_hidden() and page.locator('#hud').is_hidden() and page.evaluate('MeasureDemo.state.snapshot===null&&MeasureDemo.state.tiles.length===0&&MeasureDemo.state.targets.length===0'))
    page.keyboard.press('ArrowRight');check('退出后测量快捷键不产生结果',page.evaluate('MeasureDemo.state.targets.length')==0)
    page.click('#entry-rec');check('退出后可通过Recorder模拟入口新建会话',page.evaluate('MeasureDemo.state.session')==sid+1)
    check('没有浏览器脚本异常',not errors,str(errors))
    page.select_option('#fixture','region');page.evaluate("document.getElementById('toast').hidden=true");page.screenshot(path=str(evidence/'05-final-region.png'))
    browser.close()
(evidence/'browser-tests.json').write_text(json.dumps({'scope':'In-memory Chromium HTML prototype; not native OS acceptance','cases':results,'pass':sum(x['status']=='PASS' for x in results),'errors':errors},ensure_ascii=False,indent=2), encoding='utf-8')
print(json.dumps({'tests':len(results),'pass':sum(x['status']=='PASS' for x in results),'errors':errors},ensure_ascii=False))
