package recorder

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"strings"
	"text/template"
)

type CompileOptions struct {
	ReplayConfigPath string
}

func (m *Manager) Compile(sessionID string, flow Flow, options CompileOptions) (string, error) {
	if flow.Mode != "deterministic" {
		return "", errors.New("only deterministic flow compilation is supported")
	}
	if len(flow.Steps) == 0 {
		return "", errors.New("cannot compile an empty flow")
	}
	for index, step := range flow.Steps {
		if len(step.SourceActionIDs) == 0 {
			return "", fmt.Errorf("step %d has no sourceActionIds", index+1)
		}
		if step.Action.Name == "click" && len(step.Locators) == 0 {
			return "", fmt.Errorf("click step %d has no locator", index+1)
		}
	}
	if options.ReplayConfigPath == "" {
		options.ReplayConfigPath = "generated/replay-config.json"
	}
	flowJSON, err := json.MarshalIndent(flow, "", "  ")
	if err != nil {
		return "", err
	}
	data := struct {
		FlowJSON         string
		ReplayConfigPath string
	}{FlowJSON: string(flowJSON), ReplayConfigPath: options.ReplayConfigPath}
	var buffer bytes.Buffer
	if err := template.Must(template.New("flow").Parse(generatedJavaScript)).Execute(&buffer, data); err != nil {
		return "", err
	}
	path, err := m.store.ArtifactPath(sessionID, "generated/flow.js")
	if err != nil {
		return "", err
	}
	if err := os.WriteFile(path, buffer.Bytes(), 0o644); err != nil {
		return "", err
	}
	return path, nil
}

const generatedJavaScript = `/**
 * Generated by OpenDesk Agent-first Recorder.
 * Mode: deterministic. This script contains no Codex, LLM, planner, or AI locator repair call.
 */

const FLOW = {{.FlowJSON}};
const REPLAY_CONFIG_PATH = {{printf "%q" .ReplayConfigPath}};

// Human-readable business steps are intentionally visible before helpers.
const STEPS = FLOW.steps.map((step) => ({
  stepId: step.stepId,
  intent: step.intent,
  target: step.target,
  sourceActionIds: step.sourceActionIds,
  action: step.action.name,
  expectedPostconditions: step.expectedPostconditions,
}));

async function main() {
  assertDeterministicRuntime();
  const config = readOptionalJSON(REPLAY_CONFIG_PATH) || {};
  const report = { schemaVersion: FLOW.schemaVersion, flowId: FLOW.flowId, mode: 'deterministic', ok: false, steps: [], wrongTargetClicks: 0, startedAt: new Date().toISOString() };
  for (const step of FLOW.steps) {
    const result = { stepId: step.stepId, sourceActionIds: step.sourceActionIds, startedAt: new Date().toISOString(), ok: false };
    report.steps.push(result);
    await verifyPreconditions(step.preconditions || [], config);
    await executeDeterministicStep(step, config);
    await verifyPostconditions(step.expectedPostconditions || [], config);
    result.ok = true;
    result.completedAt = new Date().toISOString();
  }
  report.ok = true;
  report.completedAt = new Date().toISOString();
  if (config.reportPath && typeof File === 'object') await File.write(config.reportPath, JSON.stringify(report, null, 2));
  console.log(JSON.stringify(report));
  return report;
}

function assertDeterministicRuntime() {
  if (FLOW.mode !== 'deterministic') throw new Error('F8: flow mode is not deterministic');
  if (typeof Codex !== 'undefined' || typeof LLM !== 'undefined' || typeof AgentPlanner !== 'undefined') {
    throw new Error('F9: AI planning surface must not be present during deterministic replay');
  }
}

async function executeDeterministicStep(step, config) {
  const action = step.action || {};
  const args = action.arguments || {};
  if (action.name.startsWith('dom.')) return executeDOMAction(action.name, args);
  if (action.name === 'focusWindow') return window.focus(args.title || args.expectedWindowTitle);
  if (action.name === 'type') return keyboard.type(args.text);
  if (action.name === 'pressKey') return keyboard.press(args.key);
  if (action.name === 'hotkey') return keyboard.combination(...args.keys);
  if (action.name === 'scroll') return mouse.wheel(args);
  if (action.name === 'click') return executeDesktopClick(step, config);
  throw new Error('F5: unsupported deterministic action ' + action.name);
}

function executeDOMAction(name, args) {
  if (typeof document !== 'object') throw new Error('F0: DOM runtime is unavailable');
  const element = resolveDOMTarget(args.selector);
  if (name === 'dom.fill') { element.focus(); element.value = String(args.value || ''); element.dispatchEvent(new Event('input', {bubbles: true})); return; }
  if (name === 'dom.select') { element.value = String(args.value); element.dispatchEvent(new Event('change', {bubbles: true})); return; }
  if (name === 'dom.check') { if (!element.checked) element.click(); return; }
  if (name === 'dom.click') { element.click(); return; }
  if (name === 'dom.scroll') { element.scrollTop = Number(args.scrollTop || 0); element.dispatchEvent(new Event('scroll', {bubbles: true})); return; }
  throw new Error('F5: unsupported DOM action ' + name);
}

function resolveDOMTarget(selector) {
  if (typeof selector !== 'string' || !selector.startsWith('#')) throw new Error('F4: only stable id selectors are allowed');
  const matches = document.querySelectorAll(selector);
  if (matches.length !== 1) throw new Error('F4: DOM target is missing or ambiguous: ' + selector);
  return matches[0];
}

async function executeDesktopClick(step, config) {
  if (typeof mouse !== 'object' || typeof mouse.clickForPID !== 'function') throw new Error('F0: mouse.clickForPID is unavailable');
  const args = step.action.arguments || {};
  const state = readFreshDesktopState(config.statePath || args.statePath, config.maxStateAgeMs || 1000);
  verifyDesktopIdentity(state, args);
  const targetKey = args.targetKey;
  const hit = state.hits && state.hits[targetKey];
  const acceptedLabels = Array.isArray(args.acceptedLabels) ? args.acceptedLabels : [];
  const actualLabels = [String(hit && hit.title || '').trim(), String(hit && hit.description || '').trim()];
  if (!hit || hit.error !== 0 || hit.pid !== state.application.pid || hit.role !== 'AXButton' || hit.supportsAXPress !== true || !Array.isArray(hit.actions) || !hit.actions.includes('AXPress')) {
    throw new Error('F4: AX target is unavailable for ' + targetKey);
  }
  if (acceptedLabels.length && !actualLabels.some((label) => acceptedLabels.includes(label))) {
    throw new Error('F4: AX target label mismatch for ' + targetKey);
  }
  await mouse.clickForPID(state.application.pid, Number(hit.x), Number(hit.y));
}

function verifyDesktopIdentity(state, args) {
  const windows = state.windows || [];
  if (!state.permissions || state.permissions.screenCapture !== true || state.permissions.accessibility !== true) throw new Error('F0: required permissions are missing');
  if (!state.application || state.application.available !== true || state.application.terminated !== false) throw new Error('F0: target application is unavailable');
  if (args.expectedBundleID && state.application.bundleID !== args.expectedBundleID) throw new Error('F4: target bundle mismatch');
  if (args.expectedAppPath && state.application.bundlePath !== args.expectedAppPath) throw new Error('F4: target application path mismatch');
  if (windows.length !== 1 || windows[0].ownerPID !== state.application.pid) throw new Error('F4: target window is missing or ambiguous');
  if (!state.frontmost || state.frontmost.pid !== state.application.pid || state.application.active !== true) throw new Error('F4: target window is not foreground');
}

async function verifyPreconditions(conditions, config) {
  for (const condition of conditions) {
    if (condition.kind === 'activeWindowTitleEquals' && typeof window === 'object') {
      const active = await window.getActiveWindow();
      if (!active || active.title !== condition.value) throw new Error('F4: active window precondition failed');
    }
    if (condition.kind === 'activeExecutableEquals' && typeof window === 'object') {
      const active = await window.getActiveWindow();
      if (!active || active.exePath !== condition.value) throw new Error('F4: active executable precondition failed');
    }
  }
}

async function verifyPostconditions(conditions, config) {
  for (const condition of conditions) {
    if (condition.kind === 'displayEquals') {
      await waitForDisplay(config.statePath, condition.value, Number(config.postconditionTimeoutMs || 2000));
    } else if (condition.kind.startsWith('dom.')) {
      await waitForDOMPostcondition(condition, Number(config.postconditionTimeoutMs || 2000));
    }
  }
}

function DOMPostconditionMatches(condition) {
  const value = condition.value || {};
  const element = resolveDOMTarget(value.selector);
  if (condition.kind === 'dom.textEquals') return String(element.textContent).trim() === String(value.expected);
  if (condition.kind === 'dom.valueEquals') return String(element.value) === String(value.expected);
  if (condition.kind === 'dom.checkedEquals') return Boolean(element.checked) === Boolean(value.expected);
  throw new Error('F5: unsupported DOM postcondition ' + condition.kind);
}

async function waitForDOMPostcondition(condition, timeoutMs) {
  const started = Date.now();
  while (Date.now() - started <= timeoutMs) {
    if (DOMPostconditionMatches(condition)) return;
    await delay(25);
  }
  throw new Error('F6: DOM postcondition failed: ' + condition.kind);
}

async function waitForDisplay(statePath, expected, timeoutMs) {
  const started = Date.now();
  while (Date.now() - started <= timeoutMs) {
    const state = readFreshDesktopState(statePath, 1200);
    if (normalizeDisplay(state.mainDisplayValue) === normalizeDisplay(expected)) return;
    await page.waitForTimeout(25);
  }
  throw new Error('F6: display postcondition failed; expected ' + expected);
}

function delay(milliseconds) {
  if (typeof page === 'object' && typeof page.waitForTimeout === 'function') return page.waitForTimeout(milliseconds);
  return new Promise((resolve) => setTimeout(resolve, milliseconds));
}

function normalizeDisplay(value) { return String(value == null ? '' : value).replace(/[\s,]/g, ''); }
function readFreshDesktopState(path, maxAgeMs) {
  const state = readRequiredJSON(path);
  if (!Number.isFinite(state.timestampEpochMs) || Date.now() - state.timestampEpochMs > maxAgeMs || state.timestampEpochMs > Date.now() + 1000) throw new Error('F1: desktop state is stale');
  return state;
}
function readRequiredJSON(path) { const value = readOptionalJSON(path); if (!value) throw new Error('F1: required JSON is missing: ' + path); return value; }
function readOptionalJSON(path) { if (typeof File !== 'object' || !path || !File.exists(path)) return null; return JSON.parse(File.read(path)); }

await main();
`

func GeneratedJavaScriptUsesAI(script string) bool {
	lower := strings.ToLower(script)
	for _, token := range []string{"fetch(\"https://api.openai", "agentplanner.plan(", "llm.complete(", "codex.run("} {
		if strings.Contains(lower, token) {
			return true
		}
	}
	return false
}
