'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const vm = require('node:vm');
const repo = path.resolve(__dirname, '..', '..');
const historyFile = path.join(repo, 'examples/custom-ui/recording-console-simple/recording-history.js');
const controllerFile = path.join(repo, 'examples/custom-ui/recording-console-simple/controller.js');
const historySource = fs.readFileSync(historyFile, 'utf8');
vm.runInThisContext(historySource, {filename: historyFile});
const History = globalThis.OpenDeskRecordingHistory;

function FileAPI() { return {
  join: path.join,
  stat(p) { try { const s=fs.statSync(p); return {type:s.isDirectory()?'directory':s.isFile()?'file':'other',modifiedAt:s.mtime.toISOString()}; } catch(e){ if(e.code==='ENOENT') return null; throw e; } },
  listDir:p=>fs.readdirSync(p), read:p=>fs.readFileSync(p,'utf8'), write:(p,s)=>fs.writeFileSync(p,s),
  removeDir:p=>fs.rmSync(p,{recursive:true,force:true}), ensureDir:p=>fs.mkdirSync(p,{recursive:true}),
}; }
function recording(root,id,o={}) { const d=path.join(root,id); fs.mkdirSync(path.join(d,'generated'),{recursive:true}); fs.writeFileSync(path.join(d,'manifest.json'),JSON.stringify({recordingId:id,state:'stopped',startedAt:o.at||'2026-09-11T12:00:00Z',within:{processId:7,title:o.title===undefined?'Calculator':o.title},storage:{state:'saved'},issues:[]})); if(o.name) fs.writeFileSync(path.join(d,'ui-metadata.json'),JSON.stringify({schemaVersion:1,recordingId:id,displayName:o.name})); if(o.recipe!==false) fs.writeFileSync(path.join(d,'generated/basic.recipe.js'),'// recipe\n'); return d; }
function toolbar(){ const b=new Map([['capture',{disabled:false}],['stop',{disabled:true,callback:()=>{}}],['replay',{disabled:false}],['agentPrompt',{disabled:false}]]), c=new Map([['pointerMotion',{value:true,disabled:false}]]); return {buttons:b,controls:c,addButton(id,label,icon,callback){b.set(id,{id,label,icon,callback,disabled:false});},updateButton:async(id,p)=>Object.assign(b.get(id),p),getButtonState:async id=>({...b.get(id)}),updateControl:async(id,p)=>Object.assign(c.get(id),p),getControlState:async id=>({...c.get(id)}),addSwitch(id,l,o,cb){c.set(id,{value:!!o.value,disabled:false,callback:cb});},on(){},show:async()=>{},close:async()=>{}}; }
function UI(){ const windows=[]; return {windows,async createWindow(spec){ const controls=new Map(), listeners={}; const w={spec,controls,control(id){ if(!controls.has(id)) controls.set(id,{listeners:{},patch:{},on(t,cb){this.listeners[t]=cb;},async update(p){Object.assign(this.patch,p);}}); return controls.get(id);},on(t,cb){listeners[t]=cb;},async show(){},async close(){if(listeners.close) listeners.close({type:'close'});}}; windows.push(w); return w; }}; }
function click(w,id){ const c=w.controls.get(id); assert.ok(c&&c.listeners.click,`${id} click`); return c.listeners.click({type:'click'}); }
function fixture(o={}) { const temp=fs.mkdtempSync(path.join(os.tmpdir(),'history-click-')), root=path.join(temp,'.runtime/recordings'); fs.mkdirSync(root,{recursive:true}); const ui=UI(), tb=toolbar(), alerts=[],prompts=[],confirms=[],calls=[]; const dialog={alert:async s=>(alerts.push(s),null),prompt:async s=>(prompts.push(s),o.prompt?o.prompt(s):null),confirm:async s=>(confirms.push(s),o.confirm?o.confirm(s):false)}; const command=o.command||{run:async(...a)=>(calls.push(a),{exitCode:0,stdout:'',stderr:''})}; const manager=History.createManager({file:FileAPI(),ui,dialog,command,execution:{workdir:temp},system:{getPlatformInfo:()=>({os:o.platform||'darwin'})},toolbar:tb,app:{state:()=>({phase:'ready'})},recordingsRoot:root,platform:o.platform,runCountdownStepMs:0,logger:{error(){}}}); return {temp,root,ui,tb,alerts,prompts,confirms,calls,manager}; }
const win=f=>f.ui.windows.at(-1), clean=f=>fs.rmSync(f.temp,{recursive:true,force:true});

test('rename0 click validates, persists, refreshes immediately, and survives reopen', async()=>{ const answers=[null,'   ','bad\u0007name','x'.repeat(81),'  新名称  '], f=fixture({prompt:()=>answers.shift()}); try { recording(f.root,'rec-rename',{title:''}); await f.manager.open(); let w=win(f); await click(w,'rename0'); assert.equal(f.prompts[0].defaultValue,'rec-rename'); const meta=path.join(f.root,'rec-rename/ui-metadata.json'); assert.ok(!fs.existsSync(meta)); for(let i=0;i<3;i++) await click(w,'rename0'); assert.equal(f.alerts.length,3); await click(w,'rename0'); assert.equal(JSON.parse(fs.readFileSync(meta)).displayName,'新名称'); w=win(f); assert.match(w.spec.content.html,/新名称/); await w.close(); await f.manager.open(); assert.match(win(f).spec.content.html,/新名称/); } finally { clean(f); } });

test('rename0 stale row fails safely after prompt', async()=>{ let resolve; const f=fixture({prompt:()=>new Promise(r=>resolve=r)}); try { const d=recording(f.root,'rec-stale',{at:'2026-09-11T13:00:00Z'}); recording(f.root,'rec-keep',{at:'2026-09-11T12:00:00Z'}); await f.manager.open(); const p=click(win(f),'rename0'); fs.rmSync(d,{recursive:true,force:true}); resolve('new'); assert.equal(await p,null); assert.equal(f.alerts.length,1); assert.ok(fs.existsSync(path.join(f.root,'rec-keep'))); } finally { clean(f); } });

test('delete0 click cancel/confirm is scoped, guarded, immediate, and rejects stale/invalid rows', async()=>{ let deferred,mode='cancel'; const f=fixture({confirm:()=>mode==='defer'?new Promise(r=>deferred=r):false}); try { recording(f.root,'rec-delete',{name:'待删除',at:'2026-09-11T13:00:00Z'}); recording(f.root,'rec-keep',{name:'保留',at:'2026-09-11T12:00:00Z'}); await f.manager.open(); let w=win(f); await click(w,'delete0'); assert.ok(fs.existsSync(path.join(f.root,'rec-delete'))); const m=f.confirms[0].message; for(const s of ['待删除','rec-delete','raw','manifest','actions','generated','evidence','ui-metadata']) assert.match(m,new RegExp(s)); mode='defer'; const first=click(w,'delete0'); assert.equal(await click(w,'delete0'),false); assert.equal(f.confirms.length,2); deferred(true); assert.equal(await first,true); assert.ok(!fs.existsSync(path.join(f.root,'rec-delete'))); assert.ok(fs.existsSync(path.join(f.root,'rec-keep'))); assert.doesNotMatch(win(f).spec.content.html,/待删除/); await assert.rejects(()=>f.manager.remove('../outside'));
    w=win(f); fs.rmSync(path.join(f.root,'rec-keep'),{recursive:true,force:true}); assert.equal(await click(w,'delete0'),null); assert.equal(f.alerts.length,1); } finally { clean(f); } });

test('delete0 final rec-* symlink removes the link, not its external target', {skip:process.platform==='win32'}, async()=>{ const f=fixture({confirm:()=>true}); const outside=path.join(f.temp,'outside'); try { fs.mkdirSync(outside); fs.writeFileSync(path.join(outside,'keep.txt'),'keep'); const link=path.join(f.root,'rec-link'); fs.symlinkSync(outside,link,'dir'); await f.manager.open(); await click(win(f),'delete0'); assert.ok(!fs.existsSync(link)); assert.equal(fs.readFileSync(path.join(outside,'keep.txt'),'utf8'),'keep'); } finally { clean(f); } });

test('open0 click uses platform opener with recordingDir, never displayName as a path', async()=>{ const f=fixture({platform:'windows'}); try { recording(f.root,'rec-open',{name:'..\\not-a-path'}); await f.manager.open(); await click(win(f),'open0'); assert.equal(f.calls[0][0],'explorer.exe'); assert.equal(f.calls[0][1][0],path.join(f.root,'rec-open')); } finally { clean(f); } });

test('Run is disabled and unbound without a generated recipe', async()=>{ const f=fixture(); try { recording(f.root,'rec-none',{recipe:false}); await f.manager.open(); const w=win(f); assert.match(w.spec.content.html,/id="run0"[^>]* disabled/); assert.equal(w.controls.get('run0').listeners.click,undefined); } finally { clean(f); } });

test('run0 re-resolves recipe and safely disables stale Run', async()=>{ const f=fixture(); try { const d=recording(f.root,'rec-stale-recipe'); await f.manager.open(); fs.rmSync(path.join(d,'generated/basic.recipe.js')); assert.equal(await click(win(f),'run0'),null); assert.equal(f.calls.length,0); assert.equal(f.alerts.length,1); assert.match(win(f).spec.content.html,/id="run0"[^>]*disabled/); } finally { clean(f); } });

test('run0 click prevents duplicate execution and main toolbar Stop cancels the shared child', async()=>{ const source=fs.readFileSync(controllerFile,'utf8'), temp=fs.mkdtempSync(path.join(os.tmpdir(),'history-wrapper-')), root=path.join(temp,'.runtime/recordings'); fs.mkdirSync(root,{recursive:true}); recording(root,'rec-run'); const ui=UI(), inner=toolbar(); function FW(){return inner;} const core=`(function(g){g.OpenDeskSimpleRecordingConsole={createApp(o){const t=new o.FloatingWindow({toolbar:{maxColumns:7,maxRows:1}});t.addButton('capture','c','',()=>{});t.addButton('stop','s','',()=>g.stops++);t.addButton('replay','r','',()=>{});t.addSwitch('pointerMotion','p',{value:true},()=>{});t.addButton('agentPrompt','a','',()=>{});t.addButton('details','d','',()=>{});t.addButton('finder','f','',()=>{});return{run:async()=>{},show:async()=>{},close:async()=>{},stop:async()=>g.stops++,state:()=>({phase:'ready'}),toolbar:()=>t};}}})(globalThis)`; const F=FileAPI(), fake={...F,read:p=>String(p).endsWith('controller-core.js')?core:String(p).endsWith('recording-history.js')?historySource:F.read(p)}; const pending=[]; const command={run:(exe,args,o)=>new Promise((res,rej)=>{o.signal.addEventListener('abort',()=>rej(Object.assign(new Error('canceled'),{code:'CANCELED'})),{once:true});pending.push({exe,args,o});})}; const ctx={console,File:fake,Execution:{workdir:temp,scriptDir:path.join(temp,'examples/custom-ui')},FloatingWindow:FW,ui,Dialog:{alert:async()=>{},prompt:async()=>null,confirm:async()=>false},Command:command,System:{getPlatformInfo:()=>({os:'darwin'})},AbortController,setTimeout,clearTimeout,stops:0}; ctx.globalThis=ctx; vm.createContext(ctx); vm.runInContext(source,ctx); try { const app=ctx.OpenDeskSimpleRecordingConsole.createApp({historyCountdownStepMs:0,recordingsRoot:root}); await app.openHistory(); const w=ui.windows.at(-1), p=click(w,'run0'); assert.equal(await click(w,'run0'),null); for(let i=0;i<20&&!pending.length;i++) await new Promise(r=>setTimeout(r,0)); assert.equal(pending.length,1); assert.equal(path.basename(pending[0].args[1]),'basic.recipe.js'); assert.equal(w.controls.get('run0').patch.disabled,true); assert.equal(w.controls.get('rename0').patch.disabled,true); assert.equal(w.controls.get('delete0').patch.disabled,true); await inner.buttons.get('stop').callback({type:'click'}); assert.equal((await p).status,'canceled'); assert.equal(ctx.stops,0); assert.equal(w.controls.get('run0').patch.disabled,false); } finally { fs.rmSync(temp,{recursive:true,force:true}); } });

test('closing History while run is active cancels it', async()=>{ const pending=[]; const f=fixture({command:{run:(e,a,o)=>new Promise((res,rej)=>{o.signal.addEventListener('abort',()=>rej(Object.assign(new Error('canceled'),{code:'CANCELED'})),{once:true});pending.push(1);})}}); try { recording(f.root,'rec-close'); await f.manager.open(); const w=win(f), p=click(w,'run0'); for(let i=0;i<20&&!pending.length;i++) await new Promise(r=>setTimeout(r,0)); await w.close(); assert.equal((await p).status,'canceled'); } finally { clean(f); } });

test('run0 success/failure restore row controls', async()=>{ for(const fail of [false,true]){ const f=fixture({command:{run:async()=>{if(fail)throw Object.assign(new Error('boom'),{code:'FAIL'});return{exitCode:0};}}}); try { recording(f.root,`rec-${fail?'fail':'ok'}`); await f.manager.open(); const w=win(f), r=await click(w,'run0'); assert.equal(r.status,fail?'failed':'succeeded'); for(const id of ['run0','rename0','open0','delete0']) assert.equal(w.controls.get(id).patch.disabled,false); assert.equal(f.manager.isRunActive(),false); } finally { clean(f); } } });

test('row actions retain hit target, hover/disabled cues, tooltip, a11y label, and single-line ellipsis', async()=>{ const f=fixture(); try { recording(f.root,'rec-ui',{name:'很长很长很长的录制名称'}); await f.manager.open(); const {html,css}=win(f).spec.content; for(const [id,label] of [['run0','运行'],['rename0','改名'],['open0','打开目录'],['delete0','删除']]) assert.match(html,new RegExp(`id="${id}"[^>]*title="${label}"[^>]*aria-label="${label}"`)); for(const s of ['width: 32px','height: 32px','cursor: pointer','hover:not(:disabled)','opacity: 0.38','flex-wrap: nowrap','text-overflow: ellipsis','white-space: nowrap']) assert.ok(css.includes(s),s); } finally { clean(f); } });
