(() => {
'use strict';
const config = __CONFIG__;
const allowed = new Set(config.ids);
const send = (message) => window.chrome.webview.postMessage(message);
if (config.css) { const style = document.createElement('style'); style.textContent = config.css; (document.head || document.documentElement).appendChild(style); }
const element = (id) => { if (!allowed.has(id)) throw new Error('unknown custom UI control: ' + id); return document.getElementById(id); };
const typeFor = (id) => config.types[id] || 'unknown';
const dragRects = () => Array.from(document.querySelectorAll('[data-clawdesk-drag],[data-opendesk-drag]')).map(el => { const r=el.getBoundingClientRect(); return {x:r.x,y:r.y,width:r.width,height:r.height}; }).filter(r => r.width>0 && r.height>0);
const state = (id) => { const el = element(id); const r = el.getBoundingClientRect(); return {id, type:typeFor(id), text:el.textContent || '', icon:el.dataset.icon || '', value:('value' in el ? el.value : null), checked:('checked' in el ? !!el.checked : null), active:el.getAttribute('aria-pressed') === 'true', disabled:!!el.disabled, busy:el.getAttribute('aria-busy') === 'true', error:el.dataset.error || '', visible:!!(el.offsetWidth || el.offsetHeight || el.getClientRects().length), classes:Array.from(el.classList), imageComplete:el.tagName === 'IMG' ? !!el.complete : null, imageNaturalWidth:el.tagName === 'IMG' ? Number(el.naturalWidth || 0) : null, imageNaturalHeight:el.tagName === 'IMG' ? Number(el.naturalHeight || 0) : null, localBounds:{x:r.x,y:r.y,width:r.width,height:r.height}, screenBounds:{x:window.screenX+r.x,y:window.screenY+r.y,width:r.width,height:r.height}}; };
const toolbarState = (id) => { const value=state(id); const el=element(id); if (el.dataset.opendeskIconOnly === 'true') { value.accessibilityName=el.getAttribute('aria-label') || ''; value.iconPresentation={systemSymbol:el.dataset.iconSymbol || '',scale:Number(el.dataset.iconScale || 1),offsetX:Number(el.dataset.iconOffsetX || 0),offsetY:Number(el.dataset.iconOffsetY || 0)}; } return value; };
const states = () => config.ids.map(toolbarState);
const px = value => { const number=Number.parseFloat(value); return Number.isFinite(number) ? number : 0; };
const dialogLayout = () => { const root=document.getElementById('dialogRoot'); if (!root || !root.classList.contains('dialog')) return null; const icon=document.getElementById('dialogIcon'); const message=document.getElementById('dialogMessage'); const input=document.querySelector('.dialog-input'); const actions=document.getElementById('dialogButtons'); if (!icon || !message || !actions) return null; const rs=getComputedStyle(root); const is=getComputedStyle(icon); const ms=getComputedStyle(message); const messageHeight=Math.ceil(Math.max(message.scrollHeight,message.getBoundingClientRect().height)); const iconHeight=px(is.marginTop)+icon.getBoundingClientRect().height+px(is.marginBottom); const inputHeight=input ? px(getComputedStyle(input).marginTop)+input.getBoundingClientRect().height+px(getComputedStyle(input).marginBottom) : 0; const actionStyle=getComputedStyle(actions); const actionHeight=actions.getBoundingClientRect().height+px(actionStyle.marginBottom); const rightHeight=px(ms.marginTop)+messageHeight+px(ms.marginBottom)+inputHeight+actionHeight; return {contentHeight:Math.ceil(px(rs.paddingTop)+Math.max(iconHeight,rightHeight)+px(rs.paddingBottom)),messageHeight,inputHeight,actionHeight}; };
const update = (id, patch) => { const el = element(id); if (Object.prototype.hasOwnProperty.call(patch,'text')) { const text=String(patch.text ?? ''); el.textContent=text; if (el.tagName === 'BUTTON') { el.title=text; el.setAttribute('aria-label',text); } } if (Object.prototype.hasOwnProperty.call(patch,'icon')) el.dataset.icon=String(patch.icon ?? ''); if (Object.prototype.hasOwnProperty.call(patch,'value')) el.value = patch.value ?? ''; if (Object.prototype.hasOwnProperty.call(patch,'checked')) el.checked = !!patch.checked; if (Object.prototype.hasOwnProperty.call(patch,'active')) el.setAttribute('aria-pressed',patch.active ? 'true' : 'false'); if (Object.prototype.hasOwnProperty.call(patch,'disabled')) el.disabled = !!patch.disabled; if (Object.prototype.hasOwnProperty.call(patch,'busy')) { el.dataset.busy=patch.busy ? 'true' : 'false'; el.setAttribute('aria-busy',patch.busy ? 'true' : 'false'); } if (Object.prototype.hasOwnProperty.call(patch,'error')) { const message=String(patch.error ?? ''); el.dataset.error=message; el.setAttribute('aria-invalid',message ? 'true' : 'false'); } if (Object.prototype.hasOwnProperty.call(patch,'visible')) el.hidden = !patch.visible; if (Array.isArray(patch.classes)) el.className = patch.classes.join(' '); if (Object.prototype.hasOwnProperty.call(patch,'source')) { if (el.tagName !== 'IMG') throw new Error('source is supported only for img controls'); el.src = patch.source || ''; if (measurementOverlay) measurementOverlay.clear(); } if (Array.isArray(patch.options)) { if (el.tagName !== 'SELECT') throw new Error('options are supported only for select controls'); el.replaceChildren(...patch.options.map(o => { const option=document.createElement('option'); option.value=String(o.value); option.textContent=String(o.label); return option; })); } return state(id); };
const toolbarUpdate = (id, patch) => { update(id, patch); const el=element(id); if (el.dataset.opendeskIconOnly === 'true') { if (Object.prototype.hasOwnProperty.call(patch,'text')) el.textContent=''; const p=patch.iconPresentation; if (p && typeof p.systemSymbol === 'string') { el.dataset.iconSymbol=p.systemSymbol; el.dataset.iconScale=String(p.scale); el.dataset.iconOffsetX=String(p.offsetX); el.dataset.iconOffsetY=String(p.offsetY); } } return toolbarState(id); };
const targetFor = (event) => { const el = event.target && event.target.closest ? event.target.closest('[id]') : null; return el && allowed.has(el.id) ? el : null; };
document.addEventListener('click', event => { const el=targetFor(event); if (el && !el.disabled && el.dataset.busy !== 'true') send({type:'click',targetId:el.id,value:('value' in el ? el.value : null),checked:('checked' in el ? !!el.checked : null),bounds:state(el.id).screenBounds,localBounds:state(el.id).localBounds}); });
document.addEventListener('input', event => { const el=targetFor(event); if (el && !el.hasAttribute('data-opendesk-dialog-private-input')) send({type:'input',targetId:el.id,value:('value' in el ? el.value : null),checked:('checked' in el ? !!el.checked : null)}); });
document.addEventListener('change', event => { const el=targetFor(event); if (el && !el.hasAttribute('data-opendesk-dialog-private-input')) send({type:'change',targetId:el.id,value:('value' in el ? el.value : null),checked:('checked' in el ? !!el.checked : null)}); });
const measurementPoint = (event, el) => { const r=el.getBoundingClientRect(); const nw=el.naturalWidth||r.width, nh=el.naturalHeight||r.height; const s=Math.min(r.width/nw,r.height/nh); const w=nw*s,h=nh*s,left=r.left+(r.width-w)/2,top=r.top+(r.height-h)/2; return {u:(event.clientX-left)/w,v:(event.clientY-top)/h,left,top,width:w,height:h}; };
const measurementOverlay = (() => { if (!config.measurementTarget) return null; const el=document.getElementById(config.measurementTarget); if (!el) return null; el.style.touchAction='none'; el.style.userSelect='none'; const box=document.createElement('div'); box.style.cssText='position:fixed;pointer-events:none;border:1px solid #34a8ff;background:rgba(52,168,255,.15);z-index:2147483646;display:none'; const lens=document.createElement('div'); lens.style.cssText='position:fixed;pointer-events:none;width:96px;height:96px;border:2px solid #fff;box-shadow:0 2px 14px #000;background-repeat:no-repeat;image-rendering:pixelated;z-index:2147483647;display:none'; document.body.append(box,lens); let start=null; const paint=(event,p) => { const x=p.left+Math.max(0,Math.min(1,p.u))*p.width,y=p.top+Math.max(0,Math.min(1,p.v))*p.height; if(start){const sx=start.left+Math.max(0,Math.min(1,start.u))*start.width,sy=start.top+Math.max(0,Math.min(1,start.v))*start.height;box.style.display='block';box.style.left=Math.min(sx,x)+'px';box.style.top=Math.min(sy,y)+'px';box.style.width=Math.abs(x-sx)+'px';box.style.height=Math.abs(y-sy)+'px';} lens.style.display='block';lens.style.left=(event.clientX+18)+'px';lens.style.top=(event.clientY+18)+'px';lens.style.backgroundImage='url('+JSON.stringify(el.currentSrc||el.src).slice(1,-1)+')';lens.style.backgroundSize=(p.width*8)+'px '+(p.height*8)+'px';lens.style.backgroundPosition=(-p.u*p.width*8+48)+'px '+(-p.v*p.height*8+48)+'px'; }; const emit=(phase,event) => { const p=measurementPoint(event,el); if(p.u<0||p.v<0||p.u>1||p.v>1)return; if(phase==='pointerdown')start=p; paint(event,p); send({type:'measurement.'+phase,targetId:el.id,fields:{u:p.u,v:p.v,button:event.button,shift:event.shiftKey,alt:event.altKey,ctrl:event.ctrlKey,meta:event.metaKey}}); if(phase==='pointerup')start=null; }; el.addEventListener('pointerdown',event=>{if(event.button!==0)return;event.preventDefault();el.setPointerCapture(event.pointerId);emit('pointerdown',event);}); el.addEventListener('pointermove',event=>{if(event.buttons===1){event.preventDefault();emit('pointermove',event);}else{const p=measurementPoint(event,el);if(p.u>=0&&p.v>=0&&p.u<=1&&p.v<=1)paint(event,p);}}); el.addEventListener('pointerup',event=>{if(event.button!==0)return;event.preventDefault();emit('pointerup',event);}); el.addEventListener('pointerleave',()=>{if(!start)lens.style.display='none';}); return {clear:()=>{box.style.display='none';lens.style.display='none';start=null;}}; })();
document.addEventListener('keydown', event => { if (event.isComposing || event.defaultPrevented) return; const editing=!!(event.target&&event.target.closest&&event.target.closest('select,input,textarea')); const copy=(event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==='c'; if (config.measurementTarget && (event.key==='Escape'||copy||(!editing&&(event.key==='Enter'||event.key.startsWith('Arrow'))))) { event.preventDefault(); send({type:'measurement.key',targetId:config.measurementTarget,fields:{key:event.key,shift:event.shiftKey,alt:event.altKey,ctrl:event.ctrlKey,meta:event.metaKey}}); return; } if (event.key === 'Escape') { const cancel=document.querySelector('[data-opendesk-dialog-cancel]'); if (cancel || document.querySelector('[data-opendesk-dialog-default]')) { event.preventDefault(); send({type:'dialogCancel'}); } return; } if (event.key === 'Enter') { const button=document.querySelector('[data-opendesk-dialog-default]'); if (button && !button.disabled) { event.preventDefault(); send({type:'click',targetId:button.id,bounds:state(button.id).screenBounds,localBounds:state(button.id).localBounds}); } } });
const dialogFocus = document.querySelector('[data-opendesk-dialog-focus]'); if (dialogFocus) requestAnimationFrame(() => dialogFocus.focus());
document.addEventListener('mousedown',event=>{ if(event.button!==0 || !config.draggable) return; const el=event.target.closest('[data-clawdesk-drag],[data-opendesk-drag]'); if(el && !event.target.closest('button,input,select')) send({type:'drag'}); });
const setDraggable = (enabled) => { config.draggable = !!enabled; };
Object.defineProperty(window, '__opendesk', {value:Object.freeze({state:toolbarState,states,update:toolbarUpdate,setDraggable,dragRects}), configurable:false, writable:false});
send({type:'ready',dragRects:dragRects(),controls:states(),dialogLayout:dialogLayout()});
})();
